### ISSUE TITLE
Fails to Load With Alien Biomes When Arborium Is Installed

### ISSUE THREAD

**Issue by Shakar001** [jpanther/Dectorio#100]
This report is to say that the following error occurs.

```Failed to load mods: __Dectorio__/data-updates.lua:3:__Dectorio__/prototypes/third-party/alien-biomes.lua:129: attempt to perform arithmetic on field 'count' (a nil value) stack traceback:
__Dectorio__/prototypes/third-party/alien-biomes.lua:129: in main chunk
[C]: in function 'require'
__Dectorio__/data-updates.lua:3: in main chunk
stack traceback:
[C]: in function 'require'
__Dectorio__/data-updates.lua3: in main chunk

Mods to be disabled:
-Dectorio
```

This began popping up when I added the recently updated "Arborium" mod to my mod list while Alien Biomes was already present. I seen some reports saying that this is a direct conflict with Alien Biomes, but as of the current versions of both Alien Biomes and Dectorio working with each other on 0.17.21, the addition of the mod "Arborium" gave the Alien Biomes conflict. The game will load with Arborium and Alien Biomes, but not Dectorio, and it will load with Alien Biomes and Dectorio, but not Arborium. It will not load with all three enabled.

To test, I installed Dectorio, Alien Biomes, and Arborium.
Set Dectorio and Alien Biomes to load, Arborium to remain disabled. Game loads.
Set Dectorio, Alien Biomes, and Arborium to load, game fails to load.
Set Alien Biomes and Arborium to load, Dectorio to remain disabled. Game loads.

The issue is happening when all three are active in the mod listing.

**Comment by jpanther** [comment]
Thanks for the report. I've never tested compatibility with _Arborium_, but I can replicate your error. I'll look into it now.

In the meantime, a workaround to be able to play with all 3 mods is to edit the mod settings and uncheck the "Enable Landscaping" option in the Dectorio startup settings.

**Comment by jpanther** [comment]
I've located the issue and it's to do with the changes _Arborium_ introduces with seeds and saplings. In order to prevent Dectorio from replacing this gameplay mechanic, I'll make changes to disable direct tree crafting from wood in Dectorio when _Arborium_ is installed. That way you can only craft trees using the seeds and saplings method, and this conflict will no longer occur.
