### ISSUE TITLE
Don't copy vanilla recipes

### ISSUE THREAD

**Issue by ZXQWAS** [jpanther/Dectorio#101]
Dectorio copies the vanilla recipes of brick, concrete, landfill, cliff explosives and probably walls (I think nothing else). Pyanodon's mods replace the vanilla recipes. But with Dectorio enabled, I end up having both active. I didn't even notice it was wrong after a while into my base. I tried disabling flooring hoping it would disable the brick and concrete recipes, but it didn't. Of course, I can just ignore this and use the hardcore stuff, but it bugs me seeing that, and I'd really like to have an option to make Dectorio just use whatever recipe is available for these vanilla items, instead of copying them. Or like, don't categorize them as Dectorio items at all.

**Comment by jpanther** [comment]
Thanks for the report, although I'm not exactly sure what you're talking about. Dectorio doesn't copy vanilla items at all, and it doesn't modify their recipes. I've never played with Pyanodon's mods though so I'm not sure how they work. Can you be more specific about the problem?

**Comment by ZXQWAS** [comment]
I disabled Dectorio to check and was surprised to see what was oreviously tagged as "base -> dectorio", went to other mods, so vanilla stone/wall/etc recipes aren't disabled by py after all. This is invalid, sorry. That's for your attention.

**Comment by jpanther** [comment]
Thanks. Just so you know, the reason it shows "base > Dectorio" is because the recipes are moved to a different tab. If you don't want that functionality, just uncheck the "Separate Crafting Tab" setting.
