### ISSUE TITLE
In-laid 1x1 signs

### ISSUE THREAD

**Issue by tuxmark5** [jpanther/Dectorio#103]
The current signs don't align nicely to the tile grid (see [this](https://imgur.com/a/L2GwdkL)) They are also 1x2 in shape, which makes them awkward to place when using them with mods like nixie-tubes.

I'd like an exactly 1x1 sized sign entity that looks similar to a concrete tile or square text plate from text-plates mod.

Because the 2x1 sign (1.8x1-ish really) is so "unergonomic", i've been using constant combinator with alt-view enabled instead of a sign.

**Comment by jpanther** [comment]
Thanks for the suggestion. I can see in your use case that the signs don't make a lot of sense... that isn't what they were intended to be used for. I've had other requests for 1x1 signs though so I'll look into adding this in the future, although it might not be something I'll have time to implement right away.

**Comment by jpanther** [comment]
I've been revisiting some older requests and have decided that I won't be implementing this feature. There are now mods that provide something similar and I don't think I'd be able to do it in a better way. I'd suggest you look at mods like [Industrial Display Plates](https://mods.factorio.com/mod/IndustrialDisplayPlates) to get this functionality.
