### ISSUE TITLE
Tree placement request? 

### ISSUE THREAD

**Issue by omarflyjoemacky** [jpanther/Dectorio#104]
Hello again

I noticed the option to copy tile types (ground) in the mod settings. Ever thought about adding the same feature for trees? May not be a popular request, players hate trees. But I like placing them around the factory and would love to blueprint that. Would be an awesome feature!

Thanks!

**Comment by jpanther** [comment]
Thanks for the suggestion, are you referring to the option that makes landscaping tiles blueprintable? Unfortunately the base game doesn't have API that allows the environment entities to be part of blueprints so trees can't have this functionality, even in mods.

The best you can do is to use a mod that allows you to create saplings that grow into trees and blueprint those.

**Comment by omarflyjoemacky** [comment]
Hmmm. I wondered about that. What about a paintbrush option? It would be just as hand for placing multiple trees at a time... Does it help that the editor allows it?

**Comment by jpanther** [comment]
No, unfortunately there’s no paintbrush either. The game isn’t designed to be able to mass place entities like what you’re looking for. There are workarounds like what the belt painting mods and things do, but it’s not really something that I see would be useful for Dectorio. Summoning a wall of trees, for instance, isn’t particularly realistic.

**Comment by omarflyjoemacky** [comment]
Man, I enjoy the mod so much! Just keep up the great work.

 "The summoning of a wall of trees". That made me laugh. Thanks for the quick response.
