### ISSUE TITLE
Painted concrete not not connecting to plain concrete.

### ISSUE THREAD

**Issue by WonderDog** [jpanther/Dectorio#11]
The normal concret textures are not merging with the painted concrete.  It looks like are layering over the top of the plain concrete.
![paint concrete](https://cloud.githubusercontent.com/assets/8510324/26663013/47bde2b8-46cb-11e7-8252-3e3964042390.JPG)

**Comment by jpanther** [comment]
Ah, thanks. This is a bug from a change in v0.5.11. Fixed for the next release.

Commit 785b99abc30cf9db76f7913afa00f153e35b671c closes #11
