### ISSUE TITLE
Standard Walls

### ISSUE THREAD

**Issue by Hazy21** [jpanther/Dectorio#111]
Hello. I like using your mod until 0.17 as the standard walls are still at 0.16 graphics. any chance of upgrading this graphic to meet 0.17?

Thanks Hazy

**Comment by jpanther** [comment]
Thanks for the feedback. I'm a little confused to which item you are referring though? The only wall in Dectorio that uses vanilla graphics is the concrete wall and it is already using the 0.17 textures.

**Comment by Hazy21** [comment]
Hello James. Yes I am referring to the basic stone brick wall. I have been using your mod for a while,  which is nice. But I was wondering after watching KOS and JD plays YouTube videos why my brick wall was different in graphics. I asked JD about it and he said it’s the new 0.17 brick wall graphic. I couldn’t work it out until I moused over the brick wall under military tab and it stated it was part of your mod. So I disabled it and now I have the new brick wall graphic, which is the same as the concrete brick wall. Look at your pictures of the walls in your mod page and you will see what I mean. I hope this helps. If not. I will send pictures ok. 

Thanks Hazy21

**Comment by jpanther** [comment]
Thanks for clearing that up, I can see what you're talking about now. What you're seeing is actually the intended behaviour. The difference is that the vanilla game only has one type of wall - it's just called _Wall_ and is made from _Stone bricks_. What Dectorio does is mod that wall to make it the new _Concrete wall_ and then it creates a new _Stone wall_ item. This stone wall is meant to be a basic lower tech wall than the concrete one.

The graphics used for the _Stone wall_ are custom made for Dectorio, they aren't taken from 0.16. If you want your walls to look the same as the vanilla game, you need to either build the Concrete wall, or if you don't want to use the various wall types in Dectorio, then you can simply turn off this feature in the Mod Settings by unticking the "Enable walls" setting. That way you'll go back to having only the vanilla basic wall without any of the progression that Dectorio adds.

Does that make sense?

**Comment by Hazy21** [comment]
Hey JP. Yes mate. Makes good sense. Nice I will re enable the mod and uncheck walls. 

Cheers for the help and info mate. Good work👍

**Comment by jpanther** [comment]
No worries!
