### ISSUE TITLE
Stone Wall graphics!

### ISSUE THREAD

**Issue by kirazy** [jpanther/Dectorio#112]
I've created updated graphics for the stone wall (the brick design) using the new 0.17 wall graphics as a base.

https://mods.factorio.com/mod/dectorio-stone-wall

If you want to just integrate this into your mod, rather than have it standalone, that's fine, will happily pull my mod if you do. I didn't make an icon for the item, though...

**Comment by jpanther** [comment]
Ah thanks, this is great! Updating these textures has been on my to-do list for a long time. I'll definitely replace the old graphics with these ones.

**Comment by jpanther** [comment]
I've posted Dectorio v0.9.13 to the mod portal which includes these updated graphics.
