### ISSUE TITLE
possible incompatibility with angels inf ores 8.7

### ISSUE THREAD

**Issue by sovietsanta1** [jpanther/Dectorio#114]
Issue with angels ores 8.7 not sure which end it is on so i have reported to both mods
https://steamcommunity.com/sharedfiles/filedetails/?id=1759273258

**Comment by jpanther** [comment]
Thanks for the report - I play with Angels, but not infinite ores, so I'll check this out and see if I can find the issue.

**Comment by jpanther** [comment]
I can't actually launch the game at all, even when infinite ores is the only mod installed so it's definitely an issue on Angel's end... 

![Screen Shot 2019-06-03 at 09 08 37](https://user-images.githubusercontent.com/4462786/58768467-2e26b280-85df-11e9-8236-b1281cc058e1.png)

Looks like others have this issue too: https://mods.factorio.com/mod/angelsinfiniteores/discussion/5cf413547bc50c000bcdf76f
