### ISSUE TITLE
Text string for signs

### ISSUE THREAD

**Issue by mpcrilley** [jpanther/Dectorio#115]
Is there any way to attach a text string to a sign? Like naming it the way you can name rail stations and (by manipulating the console with commands) locomotives...
I'd like to be able to use signs as notes or information sources, but in a less obtrusive way than map notes.
As always, loving the mod and appreciate all the hard work you put in to it!
Mike
 aka "LastCallAgain" in-game

**Comment by jpanther** [comment]
Thanks for the suggestion. This isn't something I've really considered but it could be useful. I believe it is possible but I'll have to do a bit of investigating to see what is involved.

**Comment by jpanther** [comment]
I'm slowly removing support for Signs in Dectorio so this won't be part of my future plans. There are now better sign replacements available on the mod portal like _Industrial Display Plates_ or _Text Plates_ and I recommend you check them out.

**Comment by mpcrilley** [comment]
Thanks for letting me know. I've been using text plates off and on. Keep up
the great work!
Mike
