### ISSUE TITLE
Dectorio failed to load at game launch

### ISSUE THREAD

**Issue by Crysis1007** [jpanther/Dectorio#119]
See attached screenshot. Hope you can help me fix this please. I would like to use the mod.

![dectorio error at launch](https://user-images.githubusercontent.com/2058356/63100220-a0533600-bf44-11e9-9b50-ea9794ca94aa.png)

**Comment by jpanther** [comment]
Thanks for the report. I'm not sure why you're seeing this. I can't replicate this problem on my game. Please tell me what version of the base game and Dectorio you're using, as well as a full list of mods you have installed.

**Comment by Crysis1007** [comment]
So it seems Steam did not patch the game to 0.17. I realized it was still version 0.16.5. Had to reinstall Factorio to get Steam to update it's version then the issue was fixed. Sorry for the trouble.
