### ISSUE TITLE
unable to place water in 0.17.68

### ISSUE THREAD

**Issue by Selrax** [jpanther/Dectorio#124]
unable to place water in 0.17.68

will place on water that's already there but not create new water areas.

**Screenshots**

**Mod list**
If you are playing with other mods, include a list of these mods. The best way to do this is to provide a copy of `mod-list.json` from your Factorio data folder.

**Multiplayer**
If playing in multiplayer and you experience a desync, please upload a copy of your desync report.

**Additional context**

**Comment by jpanther** [comment]
I've tested this on 0.17.68 and have no issues placing water. You provided no mod list but I'm assuming you're playing with other mods? This could be a problem being introduced by another mod.

**Comment by Selrax** [comment]
there's the list i'm using ty for checking on this
[New Text Document.txt](https://github.com/jpanther/Dectorio/files/3614176/New.Text.Document.txt)

**Comment by jpanther** [comment]
I notice you've got `Waterfill_v15` enabled. I can't actually find this mod on the mod portal (I can only find the updated v17 version). Is this a custom mod based upon the old version?

**Comment by Selrax** [comment]
Ok waterfill isn't updated it was v15 removed from client and server still no luck with water placement

**Comment by jpanther** [comment]
I'm still unable to replicate your issue. I just want to check though, is it that you can't place any of the water tiles, or is it only some of them? Deep water can only be placed on existing water, but the normal water should be placable on land.

**Comment by jpanther** [comment]
Given there's been no further discussion on this issue and Factorio 0.18 has now been released, I'm going to close this one.
