### ISSUE TITLE
Broken Polish translation, I think

### ISSUE THREAD

**Issue by Cylindryk** [jpanther/Dectorio#125]
**Describe the bug**
When starting, this message appears:
Failed to load locale: Brakująca wartość w _ _Dectorio_ _/locale/pl/dectorio.cfg:7.

"Brakująca wartość w" mean "missing value in", roughly.
**How to reproduce**
Have active mod with PL locale?
And also I'm using 17.62 version of Factorio, if that changes anything.

**Screenshots**
Don't see the need here, if otherwise, please say.
**Mod list**
Well... only Dectorio is listed as mod to "shut down", so propably doesn't matter this time.
**Multiplayer**
No multi.
**Additional context**
Please fast fix? :)

**Comment by jpanther** [comment]
Ah thanks for the report. This issue has come out of a community translation where invalid characters were placed in the translated string. I'll fix it up to remove these characters and issue an update.

**Comment by vanedek** [comment]
In [mod-description] description must be in one line.

**Comment by jpanther** [comment]
This is fixed for the next release.
