### ISSUE TITLE
Painted concrete connection with normal concrete looks weird

### ISSUE THREAD

**Issue by dbeckwith** [jpanther/Dectorio#128]
**Describe the bug**
It seems like the connecting sprites between painted concrete and normal concrete are broken, it always shows the fully surrounded connection piece.

**How to reproduce**
Steps to reproduce the behaviour:
1. Put down concrete
2. Put down painted concrete next to/inside the normal concrete

**Screenshots**
Here are all the colors of painted concrete, including the vanilla hazard concrete:
![Screenshot_2019-09-29_01-57-23](https://user-images.githubusercontent.com/1279939/65827115-e4806880-e25c-11e9-9ccc-2cbcdf3a7d33.png)

**Mod list**
```actual-craft-times-remade
alien-biomes
alien-biomes-hr-terrain
aswil
AutoTrash
Blue-Ghosts
BlueprintExtensions
botbuzz
Bottleneck
CanalBuilder17
cheaper_landfill
ClosestFirst
Cursed-ELB
deadlock-beltboxes-loaders
DeadlockLargerLamp
DeadlockResearchNotifications
Dectorio
DiscoScience
echo-combinator
Epic-Artillery-Sounds
even-distribution
EvoGUI
Explosive Excavation
factoryplanner
far-reach
Flammable_Oils
Flow Control
FNEI
grappling-gun
Honk
IndustrialRevolution
Krastorio
Krastorio-graphics
laserlines
LuaCombinator2
manual-inventory-sort
ModuleInserter
multi-product-recipe-details
MushroomCloud
nicefill
Noxys_Trees
Orphan Finder
osha_safety
power-grid-comb
RealisticDecorationCleanup
Renamer
research-queue-the-old-new-thing
research_causes_evolution
ResourceLabelsContinued
rso-mod
SamTrain
Shield-FX
Side Inserters
SmartTrains
SmoothWarnings
sonaxaton-infinite-resources
stdlib
Tapeline
textplates
train-pubsub
tree_collision
UtilizationMonitor
wireless-charging-lib_v17
wireless-charging_v17
WireShortcuts
YouDied
```

**Comment by jpanther** [comment]
Thanks for the detailed report, I've been able to replicate this and it looks like it's something that's incompatible with _Industrial Revolution_. I'll do some more testing to try to work out exactly what it is that is causing it.

**Comment by jpanther** [comment]
This has been fixed for the next release.

**Comment by dbeckwith** [comment]
Awesome, thank you!
