### ISSUE TITLE
Support realistic ores for "Adds signal colors for raw resources".

### ISSUE THREAD

**Issue by Synthlight** [jpanther/Dectorio#132]
**Is your feature request related to a problem? Please describe.**
The added color (for lamps) as set by this mod, are still the original colors for iron/copper/uranium.
The [Realistic Ores](https://mods.factorio.com/mod/RealisticOres/) mod changes colors of these ores to be more realistic.
The end result is the lamp colors don't match the ores.

**Describe the solution you'd like**
 Could you add support for the [Realistic ores](https://mods.factorio.com/mod/RealisticOres/) mod so the added item signal colors match?

**Describe alternatives you've considered**
Are there any? I mean, I got 84 hours in my current game before I messed with a light progress bar and only then noticed the colors were off. Completely ignorable for me if the answer is no.

**Additional context**
![Untitled](https://user-images.githubusercontent.com/1075166/66246529-c0041080-e6e2-11e9-8926-16e1ba81ad38.png)
Top is copper (highlighted), bottom is iron.
I forgot to include uranium in the pic but it's less important as it's not as much of a change.

**Comment by jpanther** [comment]
Thanks for the suggestion. This should be an easy change so I'll look to add this into a future update.
