### ISSUE TITLE
In compatability with More Science

### ISSUE THREAD

**Issue by ianjirka** [jpanther/Dectorio#133]
Seems to be a recent thing.

 122.961 Mods to disable:Failed to load mods: The given sprite rectangle (left_top=0x0, right_bottom=64x64) is outside the actual sprite size (left_top=0x0, right_bottom=32x32).
If this is being used as an icon you may need to define the icon_size property.: __MoreScience__/graphics/icons/potion/set-01/potion-13.png

Mods to be disabled:
• Dectorio

AFAICT MoreScience is set correctly (32x32 icons and icon_size to match) - and hasn't been updated recently.

Disabling Dectorio resolves the load conflict.

**Comment by jpanther** [comment]
Thanks for the report. I’ll take a look and see what is going on here.

**Comment by SuicideParty** [comment]
Got bug too, but with remnants.png from `__base__`

**Comment by jpanther** [comment]
I'm having trouble replicating this issue. I'm trying with:
```
- Base: 0.17.74
- Dectorio: 0.9.16
- LSlib: 2019.8.30
- More Science: 0.2.9
```
The game is starting up fine and I don't see any conflicts. Are you using other mods that might be causing this issue?

**Comment by SuicideParty** [comment]
Iam at modpack of 136 mods lol, pretty hard to find one conflicting XD

**Comment by SuicideParty** [comment]
Okay, found out that conflict i have. Thats hells hard to describe, but i list all mods you need to reproduce.
https://mods.factorio.com/mod/MaintenanceMadness/downloads
https://mods.factorio.com/mod/LSlib
https://mods.factorio.com/mod/alien-biomes-hr-terrain
https://mods.factorio.com/mod/alien-biomes
https://mods.factorio.com/mod/space-exploration
https://mods.factorio.com/mod/robot_attrition
https://mods.factorio.com/mod/space-exploration-graphics
https://mods.factorio.com/mod/space-exploration-postprocess

**Comment by jpanther** [comment]
Thanks for working out where this is tripping up. I'll have a look at your PR and see if it solves the problem without causing other issues.

**Comment by SuicideParty** [comment]
Well, that can cause issues if there are 64px multilayered icons, but in my 136 mods modpack nothing went wrong. Still hope that can be fixed, cuz i love Dectorio.
