### ISSUE TITLE
Gates for diagonal rails

### ISSUE THREAD

**Issue by QBFreak** [jpanther/Dectorio#134]
I like trains. I generally end up with quite a few of them. With trains comes rails, and when you have rails and walls you end up needing gates. It's a little frustrating to be limited to gates on straight rails at 90 degree increments. I can understand that dealing with curved rails is probably quite a hassle, but I would love to see a mod (perhaps yours!) implement gates for diagonal rails (diagonal walls would be pretty cool too, we already get nice diagonals with tiles, why not walls?)

I realize this is not a small request. If it were easy they probably would have included it in vanilla by now. I have no idea what the gate logic looks like behind the scenes, can it even handle approaching trains when the track it's placed on is not "straight?" And then there's the assets required. I also understand that it might not quite fall into the scope of Dectorio. But you have all these nice pretty wall variations. My brain is quite insistent this is where it belongs :grin: 

Regardless of whether this is feasible or not, my next game is going to look nicer thanks to your wonderful mod. Keep up the good work!

**Comment by jpanther** [comment]
Hey thanks for the feedback; I've wanted diagonal gates many times too! Unfortunately what you're hoping for isn't actually possible with the current APIs provided by the game. There is no support for making diagonal walls or gates and it only allows for the existing horizontal or vertical alignments. This is why the walls don't form a diagonal pieces when you place them in the vanilla game and you end up with the zig-zag pattern.

If they ever add this functionality in the future, I'll be sure to look into implementing it, but at this stage there's not much I can do.
