### ISSUE TITLE
Startup option to disable grid concrete

### ISSUE THREAD

**Issue by Karl-D-Asmussen** [jpanther/Dectorio#136]
Add a tick-box option to disable the grid concrete tile (recipe, etc.) for the purpose of interaction with mods that re-texture normal concrete to the old tile look.

**Comment by SuicideParty** [comment]
Well, i didnt used Dectorio for a long time, since that crash game with my mods, but as i remember there is tick-box for old concrete

**Comment by jpanther** [comment]
The mod actually already supported this as a manual `config.lua` option but it wasn't surfaced to the player in the settings GUI. Dectorio 0.10.1 adds this as a configurable setting in-game. You can simply un-tick the "Enable Concrete Tiles" setting to disable grid concrete while retaining the other tile variants.
