### ISSUE TITLE
Separate Water and DeepWater receipts switches in mod config (for fair play)

### ISSUE THREAD

**Issue by saaadel** [jpanther/Dectorio#139]
**Is your feature request related to a problem? Please describe.**
Some mods add ability to swim through water, but not deep water. Also, without those mods we want the ability to disable both waters receipts to play fair against bitters, because them cannot swim like player.

**Describe the solution you'd like**
I suggest to add two SEPARATE checkboxes onto StartUp mods configuration tab, that can disable those two receipts (and the tech, if both disabled).
Or, even better, replace the current checkbox with a drop down with values: "none", "water only" (or "without deep-water"), "both"

**Describe alternatives you've considered**
The current alternative is to play without the ability to change other tiles, which kills the whole point of using the mod.

**Additional context**
nothing.

**Comment by jpanther** [comment]
Thanks for the suggestion, this feature is included in the next Dectorio release.

<img width="482" alt="Screen Shot 2020-04-26 at 14 29 44" src="https://user-images.githubusercontent.com/4462786/80297856-6a03d100-87ca-11ea-817e-4d9919c102b7.png">
