### ISSUE TITLE
Hazard concrete disappears after installing this mod

### ISSUE THREAD

**Issue by DRY411S** [jpanther/Dectorio#14]
This may be working as intended, but installing this mod and then loading a previously saved game that had not used this mod, the vanilla hazard-concrete is no longer available, and your modded decorative concrete is not available either as far as I can tell.

**Comment by jpanther** [comment]
This one is a known issue and seems to be a unfortunate side effect in the way the base game handles the restoration of recipes when mods are removed.

See https://mods.factorio.com/mods/PantherX/Dectorio/discussion/14333 and https://forums.factorio.com/viewtopic.php?f=25&t=47912

As per issue #13 the workaround is to set the `["disable_hazard_concrete"] = false` in config.lua and it will keep the base hazard concrete in place upon mod removal. Alternatively, you can run the command `/c game.player.force.recipes['hazard-concrete'].enabled = true` in the game console to restore the recipe.

Again, a possible solution would be for me to just leave the vanilla hazard concrete enabled by default.

**Comment by DRY411S** [comment]
But this issue is not about mod removal. It's about mod installation. A game started and saved with vanilla factorio and then loaded into factorio after this mod has been installed and enabled, finds itself with no vanilla hazard-concrete, and no alternatives from your mod.

**Comment by DRY411S** [comment]
You might be able to address this with an on_init event handler.

http://lua-api.factorio.com/latest/LuaBootstrap.html#LuaBootstrap.on_init

**Comment by DRY411S** [comment]
Oh. I'm withdrawing this issue. It's because your new decorative concrete needs to be researched.
