### ISSUE TITLE
Incompatibility between Dectorio 0.10.0 and BobWarfare 0.18.0

### ISSUE THREAD

**Issue by sejbr** [jpanther/Dectorio#141]
**Describe the bug**
Factorio crashes on startup when both Dectorio 0.10.0 and Warfare 0.18.0 are enabled.

**How to reproduce**
Just install both mods and required dependencies (I think boblibrary is the only one)

**Screenshots**
![image](https://user-images.githubusercontent.com/6895093/73025667-45e1ce00-3e30-11ea-9943-9e6920d1db2c.png)

**Mod list**
```
	{
	  "mods": 
	  [
		
		{
		  "name": "base",
		  "enabled": true
		},
	  
		{
		  "name": "boblibrary",
		  "enabled": true
		},
		
		{
		  "name": "bobwarfare",
		  "enabled": true
		},
		
		{
		  "name": "Dectorio",
		  "enabled": true
		}
	  ]
	}
```

**Multiplayer**
Not applicable

**Additional context**
I've posted this issue on Bob's forums but I've received info that It's a bug on Dectorio part.

**Comment by jpanther** [comment]
Thanks for the report. I'll aim to fix this in the next release.
