### ISSUE TITLE
Cannot use for saved game (0.5.3)

### ISSUE THREAD

**Issue by DeznekCZ** [jpanther/Dectorio#145]
**Describe the bug**
Mod failed while adding to save game.

**How to reproduce**
Steps to reproduce the behaviour:
1. Activate mod
2. Load game which not use this mod
3. See error

Error while applying migration: Dectorio: 0.5.3.lua

__Dectorio__/migrations/0.5.3.lua:20: attempt to index field 'dectorio-flooring' (a nil value)
stack traceback:
	__Dectorio__/migrations/0.5.3.lua:20: in main chunk

**Comment by jpanther** [comment]
Thanks for the report. I'll fix this in the next release.
