### ISSUE TITLE
Sprite Size 

### ISSUE THREAD

**Issue by EmberFlash** [jpanther/Dectorio#149]
**Describe the bug**
Please provide a clear and concise description of what the bug is. If the game gives you an error message, include it here. Then complete any relevant sections below (and delete those that don't apply).

**How to reproduce**
Steps to reproduce the behaviour:
When Loading the Mod there is a Sprite Size error. Not sure if there is a mismatch in code parameters, or the image is larger than needed.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/29005715/73193074-3f30b080-40e7-11ea-833c-fc7ca27a9c7b.PNG)

**Mod list**

**Multiplayer**

**Additional context**

**Comment by jpanther** [comment]
Thanks, this is a bug when playing the game with graphics sprite size set to Normal. I'll fix it in the next release.

**Comment by jpanther** [comment]
This has been fixed by #148

**Comment by EmberFlash** [comment]
Awesome Thank you.
