### ISSUE TITLE
18.2 update breaks the mod

### ISSUE THREAD

**Issue by thatguy54321** [jpanther/Dectorio#151]
Hello!  Just wanted to let you know that the 18.2 update break the mod.  I attached a screenshot of the error.  Thanks for your hard work!
![dec](https://user-images.githubusercontent.com/60396185/73276826-4a531180-41b7-11ea-84ce-85e5da365058.png)

**Comment by jpanther** [comment]
Thanks for the report. This will be fixed in the next release (will be out later today).

**Comment by jpanther** [comment]
Fixed by #154
