### ISSUE TITLE
Will this support Alien Biomes and the HD pack again in the future?

### ISSUE THREAD

**Issue by Meggars** [jpanther/Dectorio#152]
Title says it all. Loved using Dectorio with AB and with both mods updated I'm only getting a few terrain types. No tree's, which I understand with the amount of work that will be.

**Comment by jpanther** [comment]
Thanks for the question. Dectorio still supports _Alien Biomes_ and I've tested it with the latest 0.5.1 release and didn't have any issues with terrain types missing - can you be a bit more specific about what isn't showing?

With regards to the trees, there's a bug in the current release of Dectorio related to the icons of trees and rocks not displaying properly but this has been fixed in Dectorio 0.10.4 (which will be released later today).

**Comment by Meggars** [comment]
When opening the above menu I was only getting the option of 4, maybe 5, different terrain tile types to craft. Now that I've updated to .18.2 I'm getting the same error as another person posted about, so I've disabled it. I will let you know if the patch fixes the menu issue I was having and take a screenshot if it doesn't. 

Thanks for the quick reply!

**Comment by jpanther** [comment]
By any chance you don't have certain biomes disabled in the mod settings do you? If you have a biome disabled, you won't be able to craft those tiles.

**Comment by Meggars** [comment]
No, I don't have any disabled.

**Comment by jpanther** [comment]
Okay. I'm in the process of posting the Dectorio update now so you'll be able to try that soon and see if it helps.

**Comment by Meggars** [comment]
Okay, I update, now I'm getting this when trying to load my save. I hadn't used anything from Dectorio yet as it's a new game, only 2 hours in or so.
![20200128185002_1](https://user-images.githubusercontent.com/60403890/73317289-9461e480-4203-11ea-9c03-9c973ee8604d.jpg)

**Comment by jpanther** [comment]
Argh, I can fix this one too. What version of Factorio did you create this save on? Was it 0.18 or an older release?

**Comment by Meggars** [comment]
Upper right corner of the screen shot.

**Comment by jpanther** [comment]
Oh so the save was created with 0.18.2. This will be fixed in the next release.

**Comment by Meggars** [comment]
Cool. Thanks! A+ work, man. You really are the real deal.

**Comment by jpanther** [comment]
Thanks, update should be live now.

**Comment by Meggars** [comment]
Perfection! 

The menu looks smaller, did you remove some of the tiles? Not that it matters, just curious.

Also, it was the gravel that was showing up in the menu before and nothing else. Don't know if that helps at all.

Thanks so much!

**Comment by jpanther** [comment]
No, I haven't specifically removed any tiles. Alien Biomes might have though. If you play with a large modpack, I believe AB will automatically remove some of its tiles if other mods need the space as there's a hard limit of 255 tiles available in the game. Dectorio will then only show items for the tiles that are available.

If you're hitting the tile limit with your game, the best solution is to go into the AB mod settings and deselect a few of the biomes to disable them.

**Comment by Meggars** [comment]
There were more tiles than I would ever use anyway, so no biggy. I just have a very inquisitive mine. Probably on AB's end. The other big mod I'm using is Krastorio, and I'm not sure if that uses any new tiles besides assets (?). Curiosity killed the cat, and it will probably kill the Meggars as well.

**Comment by Meggars** [comment]
Nope, I was missing the painted concrete research. Now it looks normal. :)

Thanks again!

**Comment by jpanther** [comment]
Hehe, glad it was something simple! I guess I'll close this request now, but if you come across any other issues, feel free to open a new one.
