### ISSUE TITLE
Conflict with FactorioExtended Plus-Weaponry mod

### ISSUE THREAD

**Issue by Sanis25** [jpanther/Dectorio#156]
There's a load conflict since 0.10.2 with FactorioExtended Plus-Weaponry mod. Disabling Dectorio or using Dectorio 0.10.1 resolves the problem.
![conflict-dectorio](https://user-images.githubusercontent.com/60577071/73611151-820eee80-45e7-11ea-9a42-19e38aa19958.PNG)

**Comment by jpanther** [comment]
Thanks for the report but I haven't been able to replicate this. I'm running the game with these mod versions and everything is fine. Is there perhaps another mod in your modpack that is causing this conflict?

<img width="711" alt="Screen Shot 2020-02-05 at 12 36 52" src="https://user-images.githubusercontent.com/4462786/73803249-4ad15500-4814-11ea-9384-ec7dacb3d85d.png">

**Comment by Sanis25** [comment]
Yeah, I tested it with those three mods, but I found that the problem might be 'sprite resolution' setting. When sprite resolution is high, there's no problem, but when it's normal I get that error message. It would also make sense to the error message of the sprite size.

**Comment by jpanther** [comment]
Ah thanks, I can replicate this now. Let me work out what's causing it.
