### ISSUE TITLE
Colored concrete?

### ISSUE THREAD

**Issue by omarflyjoemacky** [jpanther/Dectorio#160]
Hey man! 

Is there anyway to incorporate the new colored concrete in the map editor into your mod?

**Comment by jpanther** [comment]
I didn't even realise they had added support for this in the base game! I'll definitely have a look and see if there's a way to add it into Dectorio.

**Comment by omarflyjoemacky** [comment]
Yeah makes me wonder if they are gonna create a recipe for it. But they quoted in the last FFF forums "no more new features". It'd be neat to combine elements for the colors... coal for black for instance.
