### ISSUE TITLE
Add option for waterfill only on landfill

### ISSUE THREAD

**Issue by blargh2015** [jpanther/Dectorio#161]
**Is your feature request related to a problem? Please describe.**
It's fairly game-breaking to allow waterfill on normal terrain (can make moats for biters).  If that's your thing, great, but I'd like to prohibit that on my server, but still allow using waterfill to undo landfill mistakes.

**Describe the solution you'd like**
A toggleable option that only allows the waterfill blocks to be placed on top of previously-placed landfill blocks, and NOT any standard terrain.

**Describe alternatives you've considered**
The alternative is to completely disable waterfill.

**Additional context**
None.

**Comment by jpanther** [comment]
Thanks for the suggestion. I agree it can be a bit game-breaking and that's why I chose a recipe that makes it a little more demanding to create than some of the other waterfill mods that just make it out of nothing. That said, I'll see if I can make this an option in a future update to make the placement even more restrictive.

**Comment by jpanther** [comment]
I've looked into this further and it's not possible to restrict where the Waterfill tile is placed based upon the tile it is being placed upon. The game only distinguishes between the tiles on grouped layers and so Landfill and any other normal tile (like grass) is classified in a group called `ground-tile`. Waterfill is then restricted to only be placed on tiles that match the group `ground-tile` which ends up including everything other than water.

Therefore there's no way to say it's only placeable on Landfill tiles as it's just another type of `ground-tile`. I hope that explanation makes sense but unfortunately I'll have to close this issue.
