### ISSUE TITLE
Colored signals for all modded lamps

### ISSUE THREAD

**Issue by judos** [jpanther/Dectorio#162]
Dectorio adds a lot of colored signals. However it only applies them to the small-lamp and dect-small-lamp-glow. Other mods add more lamps. E.g. [IntegratedCircuitry](https://mods.factorio.com/mod/integratedCircuitry)

It would be cool if you can add support for those lamps as well.

**Solutions**
I quickly checked your code. It seems that it is an easy change. In prototypes.signal.final-fixes I modified this:
```
local lamp = data.raw.lamp["small-lamp"]
lamp.signal_to_color_mapping = mapped_colors

local lamp_glow = data.raw.lamp["dect-small-lamp-glow"]
lamp_glow.signal_to_color_mapping = mapped_colors
```

To this generic approach:
```
for _, lamp in pairs(data.raw.lamp) do
	lamp.signal_to_color_mapping = mapped_colors
end
```

![grafik](https://user-images.githubusercontent.com/5525810/80282045-87c03000-870f-11ea-8d88-6728e1f78a63.png)

**Alternatives**
I could also support these signals in the final-fixes of IntegratedCicuitry but I think other mods would also enjoy if you directly support those signals for all lamps.

Let me know what you decide.
Cheers!

**Original request**
[IntegratedCircuitry Mod Portal post](https://mods.factorio.com/mod/integratedCircuitry/discussion/5e7e04f2304f21000dcdbd34)

**Comment by jpanther** [comment]
Thanks for the suggestion. This was probably something I meant to come back and do long ago and it slipped through the cracks. I'll definitely add this as a feature.

**Comment by jpanther** [comment]
Okay, all done and tested! This will be in the next Dectorio release. Cool mod by the way, I think I'll add Integrated Circuitry to my next play through!

<img width="1016" alt="Screen Shot 2020-04-26 at 15 10 15" src="https://user-images.githubusercontent.com/4462786/80298485-1e542600-87d0-11ea-8632-ab1d047d04e1.png">
