### ISSUE TITLE
Separate setting for lawnmower

### ISSUE THREAD

**Issue by andreasferber** [jpanther/Dectorio#164]
At the moment the "Enable landscaping" setting enables both the lawnmower and all the landscaping tile recipes. I want to have only the lawnmower to be able to remove decoratives from an area, but I don't want to have all the tile recipes (which are a lot together with Alien Biomes) clutter up the menus.

Therefore I'd like to have a separate setting to enable just the lawnmower without the other stuff tied to the "Enable landscaping" setting.

**Comment by jpanther** [comment]
Thanks @andreasferber, this is a useful addition. I'll accept the PR and release it in the next update.
