### ISSUE TITLE
Decorio with Alien Biomes throws error message when loading together

### ISSUE THREAD

**Issue by Spook2U** [jpanther/Dectorio#167]
I have the newest 0.18 version and both mods have the newest version. Both work individually, but when I load both I get this error:

![20200521005019_1](https://user-images.githubusercontent.com/14070228/82505588-64b25180-9afe-11ea-9550-575b104c3b92.jpg)

Edit: Someone in the Alien Biomes Discord pointed this out:

> tell them that in line 120 of the mentioned file, they don't check if results exist, only if max result exists.

**Comment by jpanther** [comment]
Thanks for the report, I'm unable to replicate this with both mods installed. Do you have other mods running at the same time? I can add in the extra test on the result that you've suggested but can't test to see if it fixes your specific issue.

**Comment by Spook2U** [comment]
Yeah I have bunch of mods installed. Luckily I could find the trouble maker quite fast. [Arborium](https://mods.factorio.com/mod/Arborium_Renewed) Renewed is causing problems. But only if all 3 are installed together. Any combination of two of them works fine.

I hope that helps.

**Comment by jpanther** [comment]
Ahhh this makes perfect sense now. The issue isn't actually what you mentioned but rather Dectorio has special handling for Arborium because it changes the tree mechanics. I didn't realise someone had released a new Arborium mod with a different `Arborium_Renewed` identifier so now I'm checking for that too which looks like it fixes your issue (at least, I'm running all 3 mods now and not having any problems).

**Comment by Spook2U** [comment]
Nice this sounds like a fast fix.

> The issue isn't actually what you mentioned 
Well that was just an idea from someone in the Alien Biomes discord, could have helped that's why I put it here

**Comment by jpanther** [comment]
Yep, it was helpful and I've included that additional test in this fix too just in case there's a conflict there with other mods in future as it is a potential pitfall. :)

**Comment by jpanther** [comment]
Publishing the update to the mod portal now. Let me know if there's any further issues.

**Comment by Spook2U** [comment]
Nice It's working! Thanks for the fast support.
