### ISSUE TITLE
Game doesnt start

### ISSUE THREAD

**Issue by Cylindryk** [jpanther/Dectorio#168]
Failed to load mods: File not found: _ _ base _ _ /graphics/icons/rock-big-icon.png
Mods to be disabled:
alien-biomes (0.5.4)
Dectorio (0.10.8)

Of course I reported it also on Alien Biomes mod.

**Comment by jpanther** [comment]
Thanks for the report but I can't seem to replicate this - although I am using a newer version of Alien Biomes. With Alien Biomes 0.5.5 and Dectorio 0.10.8 it seems to work fine?

**Comment by jpanther** [comment]
I still can't replicate this so I'm closing this issue as I think the Alien Biomes update fixed it.
