### ISSUE TITLE
Lawnmower can be used to crash Klonan's Transport Drones.

### ISSUE THREAD

**Issue by nicolas-lang** [jpanther/Dectorio#170]
Please see the following Report Thread in the Transport Drones Discussion area for reference:

https://mods.factorio.com/mod/Transport_Drones/discussion/5ee11947d5735e000dfdbe4f

**Comment by jpanther** [comment]
Thanks for the report, I've made some changes in the next release of Dectorio to try to work around this issue. Let me know if it's still a problem.
