### ISSUE TITLE
Make signs have same feature and interface as "signpost" from "attach notes" mod

### ISSUE THREAD

**Issue by arzic** [jpanther/Dectorio#171]
Is it possible to make the signs that comes with the Dectorio mod have the same features as the sign that comes with the Attach Notes mod? 

The sign that comes with that mod have the ability to;
- Set icon and search for icon
- Text title that is visible in game beside the sign. With different colors.  (Toggle)
- Visible on map (Toggle)
- Text box that shows up when hovering the sign. 

Thanks for an awesome mod. I really appreciate your efforts! 🥇

**Comment by jpanther** [comment]
Thanks for the request however I'm slowly removing support for Signs in Dectorio so this won't be part of my future updates. There are now better sign replacements available on the mod portal like _Industrial Display Plates_ or _Text Plates_ and I recommend you check them out.
