### ISSUE TITLE
H2O Mod incompatibility

### ISSUE THREAD

**Issue by Tahvohck** [jpanther/Dectorio#172]
**Describe the bug**
When [H2O](https://mods.factorio.com/mod/H2O) is installed, steam is removed, and the signals for lamps break as a result.

**How to reproduce**
Steps to reproduce the behaviour:
1. Download H2O and Dectorio
2. Enable both
3. Wait for restart

**Screenshots**
![image](https://user-images.githubusercontent.com/1668722/85966332-6be63e00-b98d-11ea-91d9-f6d9c3c28085.png)

**Mod list**
N/a (Direct conflict between two mods)

**Multiplayer**
N/a

**Additional context**
N/a

**Comment by jpanther** [comment]
Thanks for the report. I'll fix this for the next release.
