### ISSUE TITLE
Add signal icons to signs

### ISSUE THREAD

**Issue by jferrazza** [jpanther/Dectorio#174]
I was disappointed that I couldn't add signal icons to signs. Is it possible you can make that happen? It would be good to have pictograms on the sign. Right now I have painted concrete on it instead.

P.S. Maybe also add text to it, maybe in the form of a status.

**Comment by jpanther** [comment]
Thanks for the request however I'm slowly removing support for Signs in Dectorio so this won't be part of my future updates. There are now better sign replacements available on the mod portal like _Industrial Display Plates_ or _Text Plates_ and I recommend you check them out.
