### ISSUE TITLE
Dectorio + Alien Biomes => snow decoratives disappear

### ISSUE THREAD

**Issue by ForrestCinelli** [jpanther/Dectorio#179]
**Describe the bug**
In Alien Biomes (with High-Res Textures), certain snow decoratives (the ones that look like bits of stone that are peeking out through the snow) behave a bit differently from other decoratives, in that they don't disappear when you build on top of them. It makes sense, since stone is a reasonable foundation for a building.

When you enable Dectorio and Alien Biomes together, however, these decoratives are treated normally: they disappear when you build on them. 

**How to reproduce**
1. Open a new game with Dectorio and Alien Biomes, and find some snow. (you can increase the `Temperature: Cold Coverage` parameter if you want your world to have more snow)
2. Build any structure (e.g. assembler or power pole) on any stone decorative, see it disappear. 

**Screenshots**
*Before:*
![image](https://user-images.githubusercontent.com/4729019/92337855-4d31b100-f07a-11ea-97ed-9233b2d85d9b.png)

*After:*
![image](https://user-images.githubusercontent.com/4729019/92337835-33906980-f07a-11ea-8d27-d7c370654dc7.png)

**Mod list**
```
{
  "mods": 
  [
    
    {
      "name": "base",
      "enabled": true
    },
    
    {
      "name": "alien-biomes",
      "enabled": true
    },
    
    {
      "name": "alien-biomes-hr-terrain",
      "enabled": true
    },
    
    {
      "name": "Dectorio",
      "enabled": true
    }
  ]
}
```

**Multiplayer**
Occurs in single player.

**Comment by jpanther** [comment]
Thanks for the report. I'll add a new mod setting in the next release to allow you to disable this behaviour.
