### ISSUE TITLE
Repairing signs

### ISSUE THREAD

**Issue by RapidMinimumBeaver** [jpanther/Dectorio#180]
**Describe the bug**
When signs ( at least wooden ) are damaged, you cannot repair them like a normal collision object. I am not, however, sure if this is because Bob's changes the repair packs. Signs that are picked up do not appear to have a health 'memory' though and you can fix them by removing and replacing the sign.

**How to reproduce**
1. Hit sign with car / shoot with gun
2. Notice that repair packs do nothing to signs!

**Mod list**

{
  "mods": 
  [
    
    {
      "name": "base",
      "enabled": true
    },
    
    {
      "name": "alien-biomes",
      "enabled": true
    },
    
    {
      "name": "AsphaltRoads",
      "enabled": true
    },
    
    {
      "name": "bobassembly",
      "enabled": true
    },
    
    {
      "name": "bobclasses",
      "enabled": true
    },
    
    {
      "name": "bobelectronics",
      "enabled": true
    },
    
    {
      "name": "bobenemies",
      "enabled": true
    },
    
    {
      "name": "bobequipment",
      "enabled": true
    },
    
    {
      "name": "bobgreenhouse",
      "enabled": true
    },
    
    {
      "name": "bobinserters",
      "enabled": true
    },
    
    {
      "name": "boblibrary",
      "enabled": true
    },
    
    {
      "name": "boblogistics",
      "enabled": true
    },
    
    {
      "name": "bobmining",
      "enabled": true
    },
    
    {
      "name": "bobmodules",
      "enabled": true
    },
    
    {
      "name": "bobores",
      "enabled": true
    },
    
    {
      "name": "bobplates",
      "enabled": true
    },
    
    {
      "name": "bobpower",
      "enabled": true
    },
    
    {
      "name": "bobrevamp",
      "enabled": true
    },
    
    {
      "name": "bobtech",
      "enabled": true
    },
    
    {
      "name": "bobvehicleequipment",
      "enabled": true
    },
    
    {
      "name": "bobwarfare",
      "enabled": true
    },
    
    {
      "name": "Bottleneck",
      "enabled": true
    },
    
    {
      "name": "cargo-ships",
      "enabled": true
    },
    
    {
      "name": "CleanedConcrete",
      "enabled": true
    },
    
    {
      "name": "clock",
      "enabled": false
    },
    
    {
      "name": "Dectorio",
      "enabled": true
    },
    
    {
      "name": "Evolution Reduction",
      "enabled": true
    },
    
    {
      "name": "Extended_Crashsite",
      "enabled": true
    },
    
    {
      "name": "Fill4Me",
      "enabled": true
    },
    
    {
      "name": "flib",
      "enabled": true
    },
    
    {
      "name": "IslandStart",
      "enabled": true
    },
    
    {
      "name": "minime",
      "enabled": true
    },
    
    {
      "name": "moreammo",
      "enabled": true
    },
    
    {
      "name": "NextGenEvolution",
      "enabled": true
    },
    
    {
      "name": "PavementDriveAssist",
      "enabled": true
    },
    
    {
      "name": "PickerAtheneum",
      "enabled": true
    },
    
    {
      "name": "PickerDollies",
      "enabled": true
    },
    
    {
      "name": "PickerExtended",
      "enabled": true
    },
    
    {
      "name": "PickerInventoryTools",
      "enabled": true
    },
    
    {
      "name": "RecipeBook",
      "enabled": true
    },
    
    {
      "name": "reskins-bobs",
      "enabled": true
    },
    
    {
      "name": "reskins-library",
      "enabled": true
    },
    
    {
      "name": "rso-mod",
      "enabled": true
    },
    
    {
      "name": "stdlib",
      "enabled": true
    },
    
    {
      "name": "TinyStart",
      "enabled": true
    },
    
    {
      "name": "TreeCleaner",
      "enabled": false
    },
    
    {
      "name": "tree_collision",
      "enabled": true
    }
  ]
}

**Comment by jpanther** [comment]
Thanks for the request however I'm slowly removing support for Signs in Dectorio so this won't be part of my future updates. There are now better sign replacements available on the mod portal like _Industrial Display Plates_ or _Text Plates_ and I recommend you check them out.
