### ISSUE TITLE
Request removal of obsolete IR 1.0.x support

### ISSUE THREAD

**Issue by Deadlock989** [jpanther/Dectorio#181]
**Describe the bug**

I am planning a re-release of Industrial Revolution later this year. Dectorio currently supports IR 1.0.x's decorative tiles. However, these no longer exist in IR 2. All of third-party/industrial-revolution.lua is now obsolete. However, it assumes the existence of tiles such as "stone-gravel" which no longer exist, which prevents Dectorio from loading when IR 2 is installed.

IR 2 currently has no decorative tiles, I would maybe like to add some at a later date, but even if that happens they are unlikely to be gravel-type flooring. Suggest that you just comment out that file completely for now.

Cheers

**Comment by jpanther** [comment]
Thanks for the heads up. I'll remove this in the next update.

**Comment by Deadlock989** [comment]
Thanks for this.

In the end I kept two of the six floorings but they are a little different. I have added support for Dectorio along the same lines as what your support was trying to do, i.e. preserving layer order so that Dectorio and IR gravels are below bricks and concrete.
