### ISSUE TITLE
Mods mismatch detected! on headless server

### ISSUE THREAD

**Issue by jjw123** [jpanther/dectorio#183]
**Describe the bug**
I know we're using a lot of mods here, so I apologise it's gonna be hell to try and reproduce/figure out. Basically the server launches fine, but whenever anybody tries to connect we get the following message:

Mods Mismatch detected!
Dectorio: Mod contents are different even though the versions are the same. The most common cause of this is improper mod setting usage (conditionally requiring files based on mod settings). This can also be caused by modifying mod files on the client or server but not the other.

The server launches fine when Dectorio is removed, single player also works fine with Dectorio enabled. The exact same Dectorio zip works fine in a different instance on the same server (different port). I'm going to keep experimenting and see if I can figure out if another mod is conflicting, but wanted to post here to see if anyone has anything immediate to try.

**Mod list**

```
248k = "0.2.11"
Aircraft = "1.7.1"
AsphaltRoads = "1.2.0"
AutoDeconstruct = "0.1.20"
Automatic_Train_Painter = "1.0.0"
BeltRouter = "1.3.4"
Blueprinter = "0.8.0"
Bottleneck = "0.11.5"
BurntExtractor = "0.2.4"
Dectorio = "0.10.9"
ElectricTrain = "0.18.1"
Enhanced_Map_Colors = "1.5.3"
Exoskeleton Mark II = "5.2.0"
FARL = "4.0.7"
FNEI = "0.3.4"
Factorissimo2 = "2.4.3"
FluidMustFlow = "1.2.9"
FluidWagonColorMask = "1.0.2"
FuelTrainStop = "0.18.1"
Honk = "4.1.0"
LSlib = "2020.8.22"
LogisticTrainNetwork = "1.14.6"
Long Inserters = "1.1.2"
LtnManager = "0.3.9"
MiscLib = "0.8.6"
NightvisionToggles = "1.0.3"
Noxys_Swimming = "0.3.0"
NuclearFurnace = "0.2.1"
PSiChatUtil = "0.1.1"
PavementDriveAssist = "2.2.0"
Power Armor MK3 = "0.2.20"
ProgressiveRunningRevived = "1.0.2"
RailSignalPlanner = "0.1.7"
Shuttle_Train_Continued = "0.18.1"
Squeak Through = "1.8.0"
TheFatController = "5.0.7"
Todo-List = "18.0.1"
UltimateBelts_Owoshima_And_Pankeko-Mod = "0.18.1"
Warehousing = "0.3.1"
Yuoki = "1.0.2"
aai-industry = "0.4.23"
aai-programmable-structures = "0.6.6"
aai-programmable-vehicles = "0.6.14"
aai-signal-transmission = "0.3.22"
aai-signals = "0.5.2"
aai-vehicles-chaingunner = "0.5.2"
aai-vehicles-flame-tank = "0.4.1"
aai-vehicles-flame-tumbler = "0.5.1"
aai-vehicles-hauler = "0.5.1"
aai-vehicles-laser-tank = "0.5.2"
aai-vehicles-miner = "0.5.9"
aai-vehicles-warden = "0.4.2"
aai-zones = "0.5.2"
accumulator-wagon = "0.18.0"
alien-biomes = "0.5.8"
alien-biomes-hr-terrain = "0.5.1"
angels-smelting-extended = "1.0.4"
angelsaddons-cab = "0.2.4"
angelsaddons-mobility = "0.0.3"
angelsaddons-storage = "0.0.2"
angelsbioprocessing = "0.7.16"
angelsexploration = "0.3.8"
angelsindustries = "0.4.8"
angelspetrochem = "0.9.16"
angelsrefining = "0.11.18"
angelssmelting = "0.6.13"
base = "1.0.0"
bbr-fix = "0.18.4"
beautiful_bridge_railway = "0.18.1"
beautiful_bridge_railway_bob_fix_updated = "0.1.6"
belt-brush = "0.7.1"
blueprint_flip_and_turn = "100.8.5"
bobassembly = "1.0.0"
bobclasses = "1.0.0"
bobelectronics = "1.0.0"
bobenemies = "1.0.0"
bobequipment = "1.0.0"
bobgreenhouse = "1.0.0"
bobinserters = "1.0.1"
boblibrary = "1.0.0"
boblogistics = "1.0.0"
bobmining = "1.0.0"
bobmods_gfxtweak = "0.18.0"
bobmodules = "1.0.0"
bobores = "1.0.0"
bobplates = "1.0.2"
bobpower = "1.0.0"
bobrevamp = "1.0.1"
bobtech = "1.0.0"
bobvehicleequipment = "1.0.1"
bobwarfare = "1.0.0"
car-finder = "1.4.1"
cargo-ships = "0.0.56"
clock = "1.0.0"
concreted-rails = "0.18.0"
even-distribution = "0.3.18"
far-reach = "1.0.1"
flib = "0.5.0"
heat_glow = "0.18.1"
helmod = "0.11.19"
jetpack = "0.1.25"
miniloader = "1.12.3"
railloader = "1.0.7"
rso-mod = "6.1.4"
spidertron-extended = "0.3.5"
spidertron-follow = "0.1.1"
trainConstructionSite = "0.2.11"
yi_engines = "1.0.45"
yi_railway = "0.8.27"
z_yira_UP = "0.8.12"
z_yira_american = "0.8.10"
z_yira_yuokirails = "0.8.18"
```

**Comment by jpanther** [comment]
Thanks for the report. You're right that these issues aren't always straightforward to track down. Out of interest have you tried using the latest 0.11 version of Dectorio? It's weird that you're only having the issue on one instance.

**Comment by jjw123** [comment]
yeah the 0.11 version had the same issue. I switched to 0.10.9 as that's the same version as what's on the working instance. I will try removing all mods and adding one at a time

**Comment by Steveplays28** [comment]
I'm also having this issue, I'm trying to see if Dectorio's signals are the issue.

**Comment by jjw123** [comment]
So I removed everything and added them one at a time. And now everything works together.

So I'm guessing it's a mod load issue that I accidentally fixed?

**Comment by feyd** [comment]
I just got this issue now too on a new headless server. If I remove Dectorio all works fine, but if I copy Dectorio from my machine to the server I get the mod mismatch.

**Comment by jpanther** [comment]
I'm guessing this has something to do with how final-fixes being applied differently when a certain mod is loaded in a different order. If everyone can post their mod lists it might help narrow down which other mod(s) might be causing the conflict to arise.

**Comment by jpanther** [comment]
Can anyone confirm if this is still an issue using the latest version of Dectorio?

**Comment by feyd** [comment]
I am still getting it with 0.11.1

mods list here:

Actual_Craft_Time 0.5.8 
Automatic_Train_Painter 1.0.0 
Bottleneck_WithDrill 0.11.8 
Concrete-Tints 1.2.0 
DeadlockLargerLamp 1.3.1 
Dectorio 0.11.1 
DiscoScience 1.0.2 
EvenMoreTextPlates 1.1.0 
FactorioExtended-Plus-CompoundSolars 1.0.0 
FactorioExtended-Plus-Core 1.0.0 
FactorioExtended-Plus-Equipment 1.0.0 
FactorioExtended-Plus-Logistics 1.0.1 
FactorioExtended-Plus-Machines 1.0.2 
FactorioExtended-Plus-Module 0.1.9 
FactorioExtended-Plus-Power 1.0.2 
FactorioExtended-Plus-Storage 1.0.1 
FactorioExtended-Plus-Transport 1.0.2 
FactorioExtended-Plus-Weaponry 1.0.2 
Factorissimo2 2.4.5 
Fill4Me 0.9.4 
FluidWagonColorMask 1.0.2 
IndustrialDisplayPlates 0.18.5 
InlaidLampsExtended 0.1.9 
LTN_Content_Reader 0.3.5 
LTN_Helper 0.1.0 
LabDansen 0.0.2 
LogisticTrainNetwork 1.14.6 
MaxRateCalculator 3.4.47 
MxlChievements 1.2.0 
Nanobots 3.2.10 
NicerFuelGlow 1.0.13 
OutpostPlannerUpdated 1.1.6 
RecipeBook 2.3.1 
SpaceMod 1.0.0 
Squeak Through 1.8.0 
UtilizationMonitorBlargh 0.7.1 
VehicleSnap 1.18.3 
YARM 0.8.102 
base 1.0.0 
beatrix 1.0.3 
bullet-trails 0.5.1 
even-distribution 0.3.18 
factoryplanner 1.0.13 
flib 0.5.0 
inbuilt_lighting 19.1.10 
nixie-tubes 0.18.5 
production-monitor 1.0.1 
spawner-alert 0.1.6 
textplates 0.5.3 
tree_collision 1.0.0

**Comment by bathrobehero** [comment]
Same issue but only with a friend. I have a headless server and I can connect but he can't (mod mismatch) but without Dectorio he can. Factorio and every mod version is the same so it's weird.

**Comment by jpanther** [comment]
This is definitely a weird one that I think is specific to the load order. I'm currently playing a Space Exploration campaign with a friend on a headless server and have had no issues with mod mismatches.

**Comment by jpanther** [comment]
This issue hasn't had any updates for quite some time so I am assuming it's no longer a problem. If there's still incompatibilities with the latest releases of these mods, please add further information.

**Comment by robot256** [comment]
This issue still exists.  The most accurate error message Factorio gave is "Mod contents mismatch even though version numbers are the same.  Probably due to misuse of mod settings."  There are two "require" statements during the data phase that are still inside conditionals, one in `decoratives.lua` and one in `walls.lua`.  If the server and client start with those settings set differently, the game will not progress to the setting sync phase and you can never connect.  Moving those lines to above the `IF DECT.ENABLED ... then` block allows the mod setting sync process to complete.

In the current release, I believe this is one of the sources of silent connection failures I am experiencing, which has been very difficult to debug.  The game does not always give the above error message for some reason.
