### ISSUE TITLE
Dectorio (0.12.0): Error while running event Dectorio::on_configuration_changed: __Dectorio__/control.lua:59: attempt to call global 'init_commands' (a nil value)

### ISSUE THREAD

**Issue by Synthlight** [jpanther/Dectorio#189]
**Describe the bug**
```
  28.815 Error AppManagerStates.cpp:1589: The mod Dectorio (0.12.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Dectorio::on_configuration_changed
__Dectorio__/control.lua:59: attempt to call global 'init_commands' (a nil value)
stack traceback:
	__Dectorio__/control.lua:59: in function <__Dectorio__/control.lua:45>
```

Happens whenever I load a save from pre-1.1.

**How to reproduce**
Load a save from pre-1.1.
Though I'm pretty sure the repro steps is just do something to trigger on configuration changed.

**Screenshots**
![image](https://user-images.githubusercontent.com/1075166/100063261-f1680000-2dfe-11eb-9150-1d18c852f86e.png)

**Additional context**
I'm pretty sure this is just calling a method removed here: https://github.com/jpanther/Dectorio/commit/012e858231eb2217f442f5dad1c4e0d915220973#diff-12b76a5b1d63b6a1a18620c4fd67f98aa90ae107b0265c6f772614b87b540af0L70
(Unless you moved it somewhere else. I grep'd through the source and only found the one call to it, no function definition.)

**Comment by JaegerJens** [comment]
I have the same error message when loading my Krastorio 2 game

**Comment by jpanther** [comment]
Thanks for the reports. This is fixed in the next release.
