### ISSUE TITLE
Hazard-Concrete can be lost when this mod is no longer used

### ISSUE THREAD

**Issue by DRY411S** [jpanther/Dectorio#19]
Your topic at the factorio forums refers

https://forums.factorio.com/viewtopic.php?t=47912

I've discovered that sometimes vanilla recipes disappear, sometimes they do not, depending on how far the user has conducted research, before disabling your mod. I raised a factorio bug report, but this has been confirmed by factorio devs to be 'working as intended'

https://forums.factorio.com/viewtopic.php?f=23&t=51014

**I believe I have a fix.** I'm not advanced enough to use Git to modify your code, so have posted here

In your items.lua add some code to hide the vanilla hazard-concrete from crafting menu

`+	-- Hide base hazard concrete item
+	if DECT.CONFIG["disable_hazard_concrete"] then
+		table.insert(
+        data.raw.item["hazard-concrete"].flags,"hidden"
+        )
+	end
`
In your recipes.lua, hide the vanilla hazard-concrete recipe where you disable the recipe. (This may not be necessary)

`data.raw["recipe"]["hazard-concrete"].hidden = true`

In your control.lua, add a handler for the 'research_finished' event. In the handler enable the hazard-concrete recipe when the vanilla 'concrete' technology has been researched.

`+local function on_research_finished(event)
+    init_global()
+    
+    -- If unlocking of vanilla recipes has been removed from technology effects,
+    -- they need to be unlocked manually in case the user wants to stop using this mod
+    -- later in the game and revert to vanilla

+	for _, nextforce in pairs(game.forces) do
+		force = nextforce
+		if event.research.name == "concrete" then
+                    force.recipes["hazard-concrete"].enabled = true
+		end
+	end
+end
+
`

In your control.lua, register the handler

`+script.on_event(defines.events.on_research_finished,function(event)
+	if event.name == defines.events.on_research_finished then
+        on_research_finished(event)
+    end
 +end)`

New code files attached with .txt extension as Git does not support attachment of .lua files.

This solution may mean that you need to look at the other places (configuration_changed, on_init, data.lua et al) where you disable the hazard-concrete recipe. I think it's important to ensure that it is unchanged wherever possible. The secret in my fix is to hide the item from crafting menus and to use the event handler to manually unlock the recipe because you have removed it from technology.effects (to stop it displaying in the research screen). Whyen you disable your mod, even after concrete has been researched it appears that the 'hidden' flag on the hazard-concrete item is lost and so the hazard-concrete reappears in the crafting menu.

[items.txt](https://github.com/jpanther/Dectorio/files/1156245/items.txt)
[recipes.txt](https://github.com/jpanther/Dectorio/files/1156248/recipes.txt)
[control.txt](https://github.com/jpanther/Dectorio/files/1156252/control.txt)

**Comment by DRY411S** [comment]
Note the above  attached files are based off of your 0.15.12 version

**Comment by jpanther** [comment]
Thanks for the detailed post, I follow what you're saying. I'll have a play with it and see if I can get a working solution. I wonder if I remove the technology effects changes and then hide the items as you suggest, that this might mean I don't need to add the event handler. Maybe if it's hidden and you research the concrete it still marks the hidden items as researched, but I'll have to do some testing.

**Comment by DRY411S** [comment]
Removing the technology effects and hiding the recipe means that the hazard-concrete will appear on the research tab for concrete. I haven't tried hiding the item with the effects in place.

**Comment by jpanther** [comment]
Okay, I'm happy to report that your suggestion has fixed the issue! I think this will probably only work in all cases for new games that are created with the patched version of Dectorio. Existing saves (where _Concrete_ has already been researched) will likely still have issues, but there's not a great deal I can do about that. I could probably add a migration script to enable hazard-concrete if concrete has been researched, but I'm not sure if that will break something or not.

I did have to remove the `data.raw["recipe"]["hazard-concrete"].enabled = false` because this will basically keep reversing the change done by the `on_research_finished` handler but hiding the recipe makes that a non-issue.

**Comment by DRY411S** [comment]
Thanks for accepting this improvement. 

I'm not sure that it's setting the recipe.hidden property that hides it from a player's crafting menu, or whether it's adding the "hidden" string to the item.flags (in items.lua). I'm not convinced that hiding the recipe does anything at all.

What's your view?

**Comment by DRY411S** [comment]
Update.

I think setting the item's hidden flag may be unnecessary. Setting the recipe.hidden property most certainly is.

I wasn't convinced that the recipe.hidden property was being honoured by the game code, but it is.

**Comment by DRY411S** [comment]
Apologies if I'm polluting this closed issue with random thoughts.

Perhaps the solution for retrofitting the fixing of this issue is, instead of a migration script, some code in on_configuration_changed event  handler to check whether concrete has been researched ad if it has, enable the hazard-concrete recipe?

The same code would be valid in a migration script.

In both cases, the recipe's hidden property is read-only however. A prior call to reset_recipes may fix that?

**Comment by jpanther** [comment]
My testing of this suggests that setting the item to hidden is not required but you still need to hide the recipe, otherwise it does show up in crafting menus. I've since removed the code that sets the 'hidden' flag on the item.
