### ISSUE TITLE
Alien Biomes 0.6.2 layered tree icons.

### ISSUE THREAD

**Issue by EarendelGames** [jpanther/Dectorio#193]
Alien Biomes 0.6.2 removes the .icon property from tree prototypes and uses the .icons property instead. The dectorio tree item can set item.icons = tree.icons to fix the problem. 

FYI all the trees now have individual names using the localised_name property too.

**Comment by Nova3281** [comment]
Is that bug related to this error?
![20201213205935_1](https://user-images.githubusercontent.com/1025630/102011459-997e4280-3d87-11eb-9a4c-25c85ee22bed.jpg)

**Comment by EarendelGames** [comment]
I haven't checked the dectorio code, but if you can find where the tree item is made and it is structured like:
icon = tree.icon,
then adding a line for 
icons = tree.icons, 
that might let it load.

**Comment by jpanther** [comment]
Thanks @EarendelGames, I've replicated this issue. I'll get a fix out shortly.

**Comment by obxfisherman** [comment]
Thanks for the update!
