### ISSUE TITLE
Dectorio causes UserVerificationMissing on headless server

### ISSUE THREAD

**Issue by hypercast52** [jpanther/dectorio#197]
We've got a headless server running with a decent amount mods, list is attached, I am unable to connect to this server as I get user verification missing when i do on the console and a simple failure to connect on my end. 

`1768.981 ConnectionRequestReplyConfirm (type(ConnectionRequestReplyConfirm) ) from(IP ADDR:({73.174.24.96:52464}))
1768.982 Refusing connection for address (IP ADDR:({73.174.24.96:52464})), username (hypercast52). UserVerificationMissing`

we've already tried futzing with the server settings including making the server as unregulated as humanely possible and that only changes the error to a mod mismatch despite me reinstalling dectorio 4 times, stealing it from our remote host twice, stealing the mod settings file twice, and reinstalling *factorio and all of my mods* twice.

removal of dectorio from the mod list solves this problem regardless of level of security on the server (verification on or off)

[mod-list.zip](https://github.com/jpanther/Dectorio/files/6007419/mod-list.zip)

**Comment by jpanther** [comment]
Thanks for the report. This is a strange error and I haven't been able to reproduce it. Is this an existing save where you added Dectorio into the mod pack and then this issue occurred or has the mod been installed from the start?

**Comment by jpanther** [comment]
Haven't had any updates on this so I'll have to close it. If you are still having this issue, feel free to create a new issue.
