### ISSUE TITLE
Lamps not detecting colors for science packs

### ISSUE THREAD

**Issue by an-accident** [jpanther/Dectorio#198]
Colors supposedly added for science packs do not work. 
I just noticed it but honestly it might've been broken for a while (last update I guess?).
Tested it with no other mods installed. All other special signal colors work fine.

**Comment by jpanther** [comment]
Thanks, I'm aware of this issue. Something in the base game changed and it no longer sees the science packs as items. I need to do some more investigating to see what needs adjusting to make it work again.
