### ISSUE TITLE
Tile Conversion

### ISSUE THREAD

**Issue by dbiser99** [jpanther/dectorio#200]
Just want to make sure I'm not missing something...is there a way to change a special tile (concrete and refined concrete specifically) back to the base version (so it can then be turned into something else?) I haven't necessarily over produced and what I have can just stay in storage, but I have changed things over time and have some that I'm not doing anything with that I'd like to repurpose if possible.

**Comment by jpanther** [comment]
At the moment this isn't possible. It's something I've thought about though. The only problem is it ends up creating a whole heap of recipes that just convert all the different tiles and it bloats the crafting menu very quickly.

**Comment by dbiser99** [comment]
Oh good...not missing anything then. As for the added recipes, that's kind of what I was thinking even just going back to the base versions and why I didn't overtly suggest it and just made sure I wasn't missing it. And forget about cross conversions...someone probably crazy enough to want it, but that would be hundreds of recipes by the time you were done.
