### ISSUE TITLE
Higher resolution icons?

### ISSUE THREAD

**Issue by dgattey** [jpanther/dectorio#202]
**Describe the bug**
I love this mod! Thanks for providing - just a quick thing here to make my experience even better. The virtual signals (and other icons too provided by Dectorio like all the Alien Biomes tiles) are noticeably lower quality. From the screenshot you can see how they differ from other virtual signals I have from LTN and from Schall's Virtual Signals mod. Can they be updated so they look a little nicer? A higher resolution is all they need I think.

**How to reproduce**
Steps to reproduce the behaviour:
1. Make sure you're at 200% interface resolution for better recognition of the difference!
2. Look at virtual signal icons in a train station naming menu, or tiles in the crafting menu
2. Notice the lower visual quality of the icons

**Screenshots**
Both these screenshots show high quality icons first, then lower quality Dectorio icons below.
![image](https://user-images.githubusercontent.com/982182/114899567-eb7fb500-9dc7-11eb-9b33-886d00d1565e.png)
![image](https://user-images.githubusercontent.com/982182/114900006-4e714c00-9dc8-11eb-8408-e2340b373208.png)

**Mod list**
Plenty, but Dectorio alone is enough to cause this in the first place. For replicating the signals I showed in the screenshot, Alien Biomes + LTN + Schall's Virtual Signals are what I have on.

**Multiplayer**
N/A

**Additional context**
Thanks for making an awesome mod!

**Comment by jpanther** [comment]
Thanks for the report. Updating these assets is definitely on the to do list.

**Comment by dgattey** [comment]
These look better now!
