### ISSUE TITLE
Wooden barricade, the fuel of the future

### ISSUE THREAD

**Issue by TKMankind** [jpanther/Dectorio#203]
Hello,

I installed Dectorio with some friends and during a game I realized that the Wooden barricade is a bit overpowered.

A unit of wood give 2.0 MJ of fuel value.

A wooden barricade cost only 3 units of wood, so I expected it to provide 6.0 MJ of fuel. But it seems that it provides double this amount : 12.0 MJ.

The result : all my trains was fueled using wooden barricades until the rocket was launched :) as I always have too much wood for my needs. It was more practical and profitable than using coal or anything else.

Maybe it should be nerfed a bit :)

**Comment by jpanther** [comment]
Haha thanks for pointing this out. I definitely did balance this when I first added the barricades but maybe the fuel values changed at some point in the base game. I'll make the change in the next release.
