### ISSUE TITLE
Research-less wood walls

### ISSUE THREAD

**Issue by d0ob** [jpanther/dectorio#205]
Hi there ! 

I was wondering if the wood walls could be available from start ? Or if a setting about it could be added ?
Edit : _I just randomly came across a mod that adds wooden walls ! 
So maybe the issue is already obsolete lol... I'm so sorry. Could still be a nice addition though._

_Having them as an early way of building defenses, right from the start. 
Plus if they comes at the same time as brick walls they're not really as usefull anymore, besides decoration. (Wich, I understand, is the point ^^ but I'd really find it suitable that way ! I tried to look the code, it's martian language to me I don't know what I was expecting ^^ I'll use the console for now._

Thanks, in any case. 
I love the mod, really well done ! 
Regards.

**Comment by jpanther** [comment]
Hey, thanks for the suggestion. I agree that it's not really useful when the stone wall unlocks at the same time. I'll make a change to enable wooden barricades from the start without research.
