### ISSUE TITLE
Error in migration from 12.2 to 12.4 - wood wall

### ISSUE THREAD

**Issue by shadbags** [jpanther/dectorio#208]
**Describe the bug**
Updated from 12.2 to 12.4, on loading my map, get:

    Error while applying migration: DectorioL 0.12.3.lua

    __Dectorio__/migrations/0.12.3.lua:6: attempt to index field 'dect-wood-wall; (a nil value)
    stack trackback: __Dectorio__/migrations/0.12.3.lua:6: in main chunk

I do not have wood walls anywhere.

**How to reproduce**
See above.

**Mod list**
  {      "name": "base",      "enabled": true    },
    {      "name": "aai-containers",      "enabled": true    },
    {      "name": "aai-industry",      "enabled": true    },
    {      "name": "aai-signal-transmission",      "enabled": true    },
    {      "name": "alien-biomes",      "enabled": true    },
    {      "name": "bullet-trails",      "enabled": true    },
    {      "name": "combat-mechanics-overhaul",      "enabled": true    },
    {      "name": "Dectorio",      "enabled": true    },
    {      "name": "factoryplanner",      "enabled": true    },
    {      "name": "flib",      "enabled": true    },
    {      "name": "FNEI",      "enabled": true    },
    {      "name": "informatron",      "enabled": true    },
    {      "name": "jetpack",      "enabled": true    },
    {      "name": "Krastorio2",      "enabled": true    },
    {      "name": "miniloader",      "enabled": true    },
    {      "name": "ModuleInserter",      "enabled": true    },
    {      "name": "robot_attrition",      "enabled": true    },
    {      "name": "shield-projector",      "enabled": true    },
    {      "name": "space-exploration",      "enabled": true    },
    {      "name": "space-exploration-graphics",      "enabled": true    },
    {      "name": "space-exploration-graphics-2",      "enabled": true    },
    {      "name": "space-exploration-graphics-3",      "enabled": true    },
    {      "name": "space-exploration-graphics-4",      "enabled": true    },
    {      "name": "space-exploration-graphics-5",      "enabled": true    },
    {      "name": "space-exploration-postprocess",      "enabled": true    },
    {      "name": "textplates",      "enabled": true    },
    {      "name": "YARM",      "enabled": true    }

Does not happen on starting a new map.

**Comment by shadbags** [comment]
[K2SE.zip](https://github.com/jpanther/dectorio/files/7132611/K2SE.zip)
Save file attached.

**Comment by jpanther** [comment]
Thanks. I assume you have the walls setting disabled in Dectorio? I'll release a patch for this one shortly.

**Comment by jpanther** [comment]
Please try v0.12.5 and hopefully this has been fixed now!

**Comment by shadbags** [comment]
Confirmed fixed, and yes, I had those disabled (I use dect for the floors). Thanks for the quick turnaround.
