### ISSUE TITLE
Mod scenario: Editor Extensions/Testing

### ISSUE THREAD

**Issue by hazemaze** [jpanther/dectorio#216]
**Describe the bug**
I can no longer launch the mod scenario Editor Extensions/Testing when Dectorio is enabled. I don't know if it's related, but this error only occurs since I enabled Krastorio2. 

I get the following error: 

```
Error while applying migration: Dectorio: 0.8.3.lua

__Dectorio__/migrations/0.8.3.lua:11: attempt to index field 'dect-base-tree-01' (a nil value)
stack traceback:
	__Dectorio__/migrations/0.8.3.lua:11: in main chunk
```

Before I activated K2 I could use the scenario without any problems while Dectorio was activated. However, the error message refers to Dectorio. So I'm reporting it here.

**How to reproduce**
Steps to reproduce the behaviour:
1. Go to 'Single player > New game'
2. Click on 'Mod scenario: Editor Extensions/Testing'
3. See error

**Mod list**

[mod-list.txt](https://github.com/jpanther/dectorio/files/7844810/mod-list.txt) (can't upload JSON format)

**Comment by jpanther** [comment]
Thanks for reporting this. I'll look to fix it in a future update. I haven't used Krastorio 2 but I suspect that it must be disabling some base game trees and so the migration here is looking for entities that no longer exist.

If you want a quick workaround you can probably unzip the Dectorio mod and delete that migration file. I suspect it will work fine without it.

**Comment by hazemaze** [comment]
Thanks for your reply. The workaround helped.

I also noticed that the error only occurs when I try to start the scenario from the menu. An already saved scenario can be loaded without any problems.

**Comment by jpanther** [comment]
Okay this makes sense because migrations are only run once on each save. Once it knows the migration has happened, it won't try to run it again which is why the saves are loading without any issues.

**Comment by Sam-Levoir** [comment]
Hello! I was about to report this too, I get the same error when using Dectorio and Editor Extensions. Figured I would drop in and mention that this is still a conflict as of right now (Factorio 1.1.74, Dectorio 0.12.6, and Editor Extensions 1.13.7).

Anyways, thanks for the tip! Was able to disable Dectorio, make a Editor Extensions world, then re-enable and load in just fine :)

> Thanks for your reply. The workaround helped.
> 
> I also noticed that the error only occurs when I try to start the scenario from the menu. An already saved scenario can be loaded without any problems.

**Comment by VavilovAlex** [comment]
This mod had the same issue.
[github.com/kyranf/robotarmyfactorio/issues/125](https://github.com/kyranf/robotarmyfactorio/issues/125)

> The quick and easy fix is to delete the entire migrations folder. turns out this behaviour is not a bug, supposedly every single migration leading up to the current version will be run in sequence if you add the mod fresh to an existing save game for the first time. It's illogical if you ask me, but that's what is causing this error right now.
> 
> I have removed the rally flag stuff from the mod, to declutter it and I don't intend on bringing it back anymore. It's a shame that it broke the mod like this, I bet hundreds of people have encountered the issue by now, I hope they see what is required by reading here..
> 
> I will release a new version which has the migrations removed for the users, plus a few minor additional things.

**Comment by fserb** [comment]
Having the same issue.

**Comment by kawazoe** [comment]
I hit the same issue and, seeing it hasn't been addressed yet, took a few minutes to write a fix.
