### ISSUE TITLE
Compatibility with Krastorio and Alienbiomes

### ISSUE THREAD

**Issue by bigtruckin78** [jpanther/dectorio#221]
I've been playing for awhile with several mods and have had no issues. I added dectorio and the game failed to load and the error was 

Error ModManager.cpp:1588: Error in assignID: tile with name 'kr-creep' does not exist. It was removed by alien-biomes.

If I remove Dectorio then the game loads fine. I'm not sure where to even go for help so if you could point me in the right direction I would be greatly appreciated. 

I've uploaded the log if that helps. Not sure what else to do. 
[factorio-previous.log](https://github.com/jpanther/dectorio/files/8746156/factorio-previous.log)

**Comment by jpanther** [comment]
I suspect what is happening here is that the number of tiles being added by all the mods you're using is causing the game to hit the max tiles allowed. When this happens Alien Biomes starts to remove tiles from the game that it thinks are not important. One way you might be able to avoid this situation is by disabling some of the flooring variations in Dectorio or some of the biomes in Alien Biomes. If you reduce the number of tiles you're trying to load you may have some success at getting the game to load.
