### ISSUE TITLE
Dectorio - Alien Biomes and Krastorio 2 - Compatability issue

### ISSUE THREAD

**Issue by Jao247** [jpanther/dectorio#226]
I saw Dectorio and decided to include it in my current Modlist for my playthrough featuring Krastorio 2 and Space Exploration.

After adding Dectorio to the mod list it ended up causing incompatibility between Krastorio 2 and Alien Biomes. I have disabled both individually and can load in but if both mods are enabled with Dectorio then I run into the issue.

I would assume this because of a certain tile matching and being named differently or removed, Here is the image of the issue on Load: 
![image](https://user-images.githubusercontent.com/3824721/193462094-e08a1c88-c657-4725-8fe8-fd74f7a370f3.png)

Again this is only occurring once Dectorio is installed.

Not sure if this is a bug that should be posted here or on one of the other Mod pages

**Comment by xXParryXx** [comment]
https://github.com/jpanther/dectorio/issues/221#issuecomment-1133782481
your using up the entire tile set that the game is allowed to load
