### ISSUE TITLE
Failed To Load

### ISSUE THREAD

**Issue by KalebSorcyubi** [jpanther/dectorio#227]
Failed To Load Refer To Picture

Trying To Install Dectorio Again, since i found a Mod to remove the Unused Tinted Concrete From base to free up tiles

**Screenshots**

**Mod list**

{
  "mods": 
  [
    
    {
      "name": "base",
      "enabled": true
    },
    
    {
      "name": "AbandonedRuins",
      "enabled": true
    },
    
    {
      "name": "AfraidOfTheDark",
      "enabled": true
    },
    
    {
      "name": "air-filtering",
      "enabled": true
    },
    
    {
      "name": "alien-biomes",
      "enabled": true
    },
    
    {
      "name": "alien-biomes-hr-terrain",
      "enabled": true
    },
    
    {
      "name": "angelsinfiniteores",
      "enabled": false
    },
    
    {
      "name": "AutoDeconstruct",
      "enabled": true
    },
    
    {
      "name": "better-air-filtering",
      "enabled": false
    },
    
    {
      "name": "big-data-string",
      "enabled": true
    },
    
    {
      "name": "BigStorageTank",
      "enabled": true
    },
    
    {
      "name": "Big_Brother",
      "enabled": true
    },
    
    {
      "name": "Bottleneck",
      "enabled": true
    },
    
    {
      "name": "cargo-ships",
      "enabled": true
    },
    
    {
      "name": "cargo-ships-graphics",
      "enabled": true
    },
    
    {
      "name": "CleanedConcrete",
      "enabled": true
    },
    
    {
      "name": "combat-mechanics-overhaul",
      "enabled": true
    },
    
    {
      "name": "DarkNight",
      "enabled": true
    },
    
    {
      "name": "Dectorio",
      "enabled": false
    },
    
    {
      "name": "DeepMine",
      "enabled": true
    },
    
    {
      "name": "DiscoScience",
      "enabled": true
    },
    
    {
      "name": "DragonIndustries",
      "enabled": true
    },
    
    {
      "name": "Enhanced_Map_Colors",
      "enabled": true
    },
    
    {
      "name": "even-distribution",
      "enabled": true
    },
    
    {
      "name": "EvoGUI",
      "enabled": true
    },
    
    {
      "name": "FactorioExtended-Plus-Core",
      "enabled": true
    },
    
    {
      "name": "FactorioExtended-Plus-Equipment",
      "enabled": true
    },
    
    {
      "name": "FactorioExtended-Plus-Logistics",
      "enabled": true
    },
    
    {
      "name": "FactorioExtended-Plus-Machines",
      "enabled": true
    },
    
    {
      "name": "FactorioExtended-Plus-Module",
      "enabled": true
    },
    
    {
      "name": "FactorioExtended-Plus-Power",
      "enabled": true
    },
    
    {
      "name": "FactorioExtended-Plus-Storage",
      "enabled": true
    },
    
    {
      "name": "FactorioExtended-Plus-Transport",
      "enabled": true
    },
    
    {
      "name": "FactorioExtended-Plus-Weaponry",
      "enabled": true
    },
    
    {
      "name": "Factorissimo2",
      "enabled": true
    },
    
    {
      "name": "FARL",
      "enabled": true
    },
    
    {
      "name": "flib",
      "enabled": true
    },
    
    {
      "name": "Flow Control",
      "enabled": true
    },
    
    {
      "name": "FNEI",
      "enabled": true
    },
    
    {
      "name": "FuelTrainStop",
      "enabled": true
    },
    
    {
      "name": "GDIW-updated",
      "enabled": true
    },
    
    {
      "name": "Geothermal",
      "enabled": true
    },
    
    {
      "name": "heroturrets",
      "enabled": true
    },
    
    {
      "name": "InfiniteTech",
      "enabled": true
    },
    
    {
      "name": "KingsTurret-Shields",
      "enabled": true
    },
    
    {
      "name": "liborio",
      "enabled": true
    },
    
    {
      "name": "LogisticTrainNetwork",
      "enabled": true
    },
    
    {
      "name": "LtnManager",
      "enabled": true
    },
    
    {
      "name": "LTN_Combinator_Modernized",
      "enabled": true
    },
    
    {
      "name": "miniloader",
      "enabled": true
    },
    
    {
      "name": "Mining_Drones",
      "enabled": true
    },
    
    {
      "name": "modmash",
      "enabled": true
    },
    
    {
      "name": "modmashsplinter",
      "enabled": true
    },
    
    {
      "name": "modmashsplinterairpurifier",
      "enabled": true
    },
    
    {
      "name": "modmashsplinterassembling",
      "enabled": true
    },
    
    {
      "name": "modmashsplinterboom",
      "enabled": true
    },
    
    {
      "name": "modmashsplinterdefense",
      "enabled": true
    },
    
    {
      "name": "modmashsplinterelectronics",
      "enabled": true
    },
    
    {
      "name": "modmashsplinterenrichment",
      "enabled": true
    },
    
    {
      "name": "modmashsplinterexplosivedeepwater",
      "enabled": false
    },
    
    {
      "name": "modmashsplinterexplosivemining",
      "enabled": true
    },
    
    {
      "name": "modmashsplinterexplosivewater",
      "enabled": false
    },
    
    {
      "name": "modmashsplinterfishing",
      "enabled": true
    },
    
    {
      "name": "modmashsplinterfluid",
      "enabled": true
    },
    
    {
      "name": "modmashsplintergold",
      "enabled": true
    },
    
    {
      "name": "modmashsplinterlogistics",
      "enabled": true
    },
    
    {
      "name": "modmashsplinterloot",
      "enabled": true
    },
    
    {
      "name": "modmashsplinternewworlds",
      "enabled": true
    },
    
    {
      "name": "modmashsplinterrecycling",
      "enabled": true
    },
    
    {
      "name": "modmashsplinterrefinement",
      "enabled": true
    },
    
    {
      "name": "modmashsplinterregenerative",
      "enabled": true
    },
    
    {
      "name": "modmashsplinterresources",
      "enabled": true
    },
    
    {
      "name": "modmashsplintersubspacelogistics",
      "enabled": true
    },
    
    {
      "name": "modmashsplinterthem",
      "enabled": true
    },
    
    {
      "name": "modmashsplinterunderground",
      "enabled": true
    },
    
    {
      "name": "modmashsplintervalkyries",
      "enabled": true
    },
    
    {
      "name": "naked-rails_se",
      "enabled": true
    },
    
    {
      "name": "Nanobots",
      "enabled": true
    },
    
    {
      "name": "Nauvis-Post-Collapse",
      "enabled": false
    },
    
    {
      "name": "NauvisDay",
      "enabled": false
    },
    
    {
      "name": "NightBrightness",
      "enabled": true
    },
    
    {
      "name": "Noxys_StackSizeMultiplier",
      "enabled": true
    },
    
    {
      "name": "Noxys_Waterfill",
      "enabled": true
    },
    
    {
      "name": "Power Armor MK3",
      "enabled": true
    },
    
    {
      "name": "Power_To_Liquid_updated",
      "enabled": true
    },
    
    {
      "name": "RemoveTintedConcrete",
      "enabled": true
    },
    
    {
      "name": "reverse-factory",
      "enabled": true
    },
    
    {
      "name": "SolarWalls",
      "enabled": true
    },
    
    {
      "name": "SpaceMod",
      "enabled": true
    },
    
    {
      "name": "Squeak Through",
      "enabled": true
    },
    
    {
      "name": "stdlib",
      "enabled": true
    },
    
    {
      "name": "StoneWaterWell",
      "enabled": true
    },
    
    {
      "name": "Trees",
      "enabled": true
    },
    
    {
      "name": "VehicleSnap",
      "enabled": true
    },
    
    {
      "name": "Warehousing",
      "enabled": true
    }
  ]
}

![dectorio](https://user-images.githubusercontent.com/82905994/206995913-26470a2b-cf3b-4836-9706-c29476fd9d6d.JPG)

**Comment by jpanther** [comment]
This can't be fixed as it's a limitation with the base game. You'll have to disable some flooring types to bring your total below 255 layers.
