### ISSUE TITLE
Inventory too long after unlocking landscaping

### ISSUE THREAD

**Issue by Nevrai** [jpanther/dectorio#236]
After you research landscaping, your inventory becomes ridiculously tall due to the Dectorio tab having an extremely large number of rows. To me, this is too frustrating to be playable with as I have to look at the top of my screen to look at my inventory and the crafting panel, rather than in the middle, so I had to revert back to a save where I hadn’t researched landscaping.

<img width="554" alt="Screenshot 2023-06-23 162318" src="https://github.com/jpanther/dectorio/assets/59761487/5b937f87-a997-41d8-806e-fabcea28307b">

It would be fantastic if you could implement a fix for this, such as a toggle to hide or unhide the landscaping items (that doesn’t change when closing your inventory or at least defaults to hide).

**Comment by jpanther** [comment]
I don't believe there's a way for me to prevent the UI from doing this. Your best bet is to simply disable landscaping in the Dectorio settings and then you won't run into this problem.
