### ISSUE TITLE
0.6.0 disabling painted concrete throws error in migration script

### ISSUE THREAD

**Issue by Yousei9** [jpanther/Dectorio#24]
Disabling painted concrete throws an error:
`__Dectorio__/migrations/0.6.0.lua:9: attempt to index field 'dect-concrete-paint' (a nil value)`

Fix:
```
if tech["dect-concrete-paint"] and tech["dect-concrete-paint"].researched then
  rec["hazard-concrete"].enabled = true
end
```

You may want to check for similar errors on other parts that can be disabled.

**Comment by jpanther** [comment]
Ah thanks, I usually do that check but obviously missed it in the migration. Will patch it in the next release.
