### ISSUE TITLE
Can't place insertator to export the product "dirt filler"

### ISSUE THREAD

**Issue by cgggg22** [jpanther/dectorio#247]
**Describe the bug**
Can't place insertator to export the product "dirt filler". I just tested and I cant place anything because it crashes, I have to deactivate untill a fix is done :P.

**How to reproduce**
Steps to reproduce the behaviour:
1. Make an ensambling machine creating dirt filler
2. Put a red box (provider) for the bots 1 space away
3. add an insertator to export the dirt filler

**Screenshots**
![image](https://github.com/user-attachments/assets/0a5d0847-222a-44f3-a971-047ffd348f80)

**Mod list**

{
  "mods": 
  [
    
    {
      "name": "base",
      "enabled": true
    },
    
    {
      "name": "Advanced-Electric-Revamped-v16",
      "enabled": true
    },
    
    {
      "name": "Automatic_Train_Painter",
      "enabled": true
    },
    
    {
      "name": "Bottleneck",
      "enabled": true
    },
    
    {
      "name": "bright-lamp",
      "enabled": false
    },
    
    {
      "name": "BuilderBotStart",
      "enabled": true
    },
    
    {
      "name": "bullet-trails",
      "enabled": true
    },
    
    {
      "name": "calculator-ui",
      "enabled": true
    },
    
    {
      "name": "ChangeMapSettings",
      "enabled": false
    },
    
    {
      "name": "clock",
      "enabled": false
    },
    
    {
      "name": "Concretexture",
      "enabled": false
    },
    
    {
      "name": "Crafting_Speed_Research",
      "enabled": false
    },
    
    {
      "name": "Dectorio",
      "enabled": true
    },
    
    {
      "name": "DiscoScience",
      "enabled": true
    },
    
    {
      "name": "EditorExtensions",
      "enabled": true
    },
    
    {
      "name": "Enhanced_Map_Colors",
      "enabled": false
    },
    
    {
      "name": "even-distribution",
      "enabled": true
    },
    
    {
      "name": "extended-descriptions",
      "enabled": false
    },
    
    {
      "name": "far-reach",
      "enabled": true
    },
    
    {
      "name": "flib",
      "enabled": true
    },
    
    {
      "name": "FluidWagonColorMask",
      "enabled": true
    },
    
    {
      "name": "fluid_permutations",
      "enabled": false
    },
    
    {
      "name": "Infinite-Resources-Reupload",
      "enabled": true
    },
    
    {
      "name": "InfiniteTech",
      "enabled": false
    },
    
    {
      "name": "lightorio",
      "enabled": false
    },
    
    {
      "name": "mining-patch-planner",
      "enabled": true
    },
    
    {
      "name": "MiningTools_Update",
      "enabled": false
    },
    
    {
      "name": "NicerFuelGlowButUpdated",
      "enabled": false
    },
    
    {
      "name": "NightBrightness",
      "enabled": false
    },
    
    {
      "name": "Orphan Finder",
      "enabled": false
    },
    
    {
      "name": "PowerAndArmor",
      "enabled": false
    },
    
    {
      "name": "qol_research",
      "enabled": true
    },
    
    {
      "name": "QueueToFrontNG",
      "enabled": false
    },
    
    {
      "name": "RealisticFlashlight",
      "enabled": false
    },
    
    {
      "name": "RealisticReactorGlow",
      "enabled": true
    },
    
    {
      "name": "Realistic_Heat_Glow",
      "enabled": false
    },
    
    {
      "name": "rebuild-crash-site",
      "enabled": true
    },
    
    {
      "name": "resourceMarker",
      "enabled": true
    },
    
    {
      "name": "rso-mod",
      "enabled": false
    },
    
    {
      "name": "show-max-underground-distance",
      "enabled": true
    },
    
    {
      "name": "spidertron-extended",
      "enabled": false
    },
    
    {
      "name": "spidertrontiers",
      "enabled": false
    },
    
    {
      "name": "Squeak Through",
      "enabled": false
    },
    
    {
      "name": "stdlib",
      "enabled": false
    },
    
    {
      "name": "uranium_geiger",
      "enabled": false
    },
    
    {
      "name": "VehicleSnap",
      "enabled": true
    },
    
    {
      "name": "VehicleTrails",
      "enabled": false
    },
    
    {
      "name": "vtk-armor-reach",
      "enabled": false
    },
    
    {
      "name": "waterfill-retexture",
      "enabled": false
    },
    
    {
      "name": "Waterfill_v17",
      "enabled": true
    }
  ]
}

**Comment by jpanther** [comment]
Thanks, I've been able to reproduce this. Fixed in #254 and will be in the next mod update.
