### ISSUE TITLE
Error when build a chemical plant

### ISSUE THREAD

**Issue by DarkEviL88** [jpanther/dectorio#248]
**Describe the bug**
I placed a chemical plant on a stone surface and the game gave this error.

**How to reproduce**
Steps to reproduce the behaviour:
Build a chemical plant on the surface from a stone block.

**Screenshots**
![image](https://github.com/user-attachments/assets/15bfcdc3-ac91-45be-8639-db5b44e35b73)

**Mod list**
[mod-list.json](https://github.com/user-attachments/files/17613306/mod-list.json)

**Multiplayer**
solo

**Additional context**

**Comment by jpanther** [comment]
Thanks, I've been able to reproduce this. Fixed in #254 and will be in the next mod update.
