### ISSUE TITLE
error when placing a rail 

### ISSUE THREAD

**Issue by MissUnikitty** [jpanther/dectorio#252]
**Describe the bug**

The mod Dectorio (0.13.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Dectorio::on_built_entity (ID 6)
__Dectorio__/control.lua:155: attempt to index local 'entity' (a nil value)
stack traceback:
	__Dectorio__/control.lua:155: in function 'destroy_decoratives_near_entity'
	__Dectorio__/control.lua:163: in function <__Dectorio__/control.lua:162>

**How to reproduce**
Was trying to place a rail

**Screenshots**
![20241104162719_1](https://github.com/user-attachments/assets/1835ccea-7233-4cbf-862e-09183e1fbdd8)
**Mod list**

[mod-list.json](https://github.com/user-attachments/files/17620304/mod-list.json)

**Multiplayer**
N/A singleplayer

**Additional context**

**Comment by jpanther** [comment]
Thanks, I've been able to reproduce this. Fixed in #254 and will be in the next mod update.
