### ISSUE TITLE
nil reference error when attempting to place any tile on map

### ISSUE THREAD

**Issue by hawkoftheeye** [jpanther/dectorio#253]
**Describe the bug**
Please provide a clear and concise description of what the bug is. If the game gives you an error message, include it here. Then complete any relevant sections below (and delete those that don't apply).

I re-enabled the mod following the recent update, and placed the Dectorio items onto my research queue. I then attempted to place a wall tile on the map, and received the following error. The error is the same as described in #249 but I open a new issue because the repro steps differ. Apologies if this is indeed the same problem.

```
The mod Dectorio (0.13.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Dectorio::on_built_entity (ID 6)
__Dectorio__/control.lua:155: attempt to index local 'entity' (a nil value)
stack traceback:
	__Dectorio__/control.lua:155: in function 'destroy_decoratives_near_entity'
	__Dectorio__/control.lua:163: in function <__Dectorio__/control.lua:162>
```

**How to reproduce**
The nil reference error occurs as soon as I try to place any tile on the map. 
It does not matter which type of item I try to place, the resulting error is the same.

**Screenshots**
I don't think screenshots are applicable.

**Mod list**
Mod list attached
[mod-list.json](https://github.com/user-attachments/files/17622383/mod-list.json)

**Multiplayer**
N/A

Please reach out if you want any more info, and thanks for updating this mod - I have been waiting for it to become Space-Age ready!

**Comment by jpanther** [comment]
Thanks, I've been able to reproduce this. Fixed in #254 and will be in the next mod update.
