### ISSUE TITLE
Decorative Colors vs Color Signals "Conflict"

### ISSUE THREAD

**Issue by abordoli** [jpanther/Dectorio#26]
As we know, your mod will warn about conflicts of other mods.

https://mods.factorio.com/mods/zx64/more-colours

^^This is one of those it warns off.

Here is the issue...

I "like" the colours it offers because some of them look like ore colors...hey, they even have a brown "wood" looking color.

Your mod doesn't have that and several others for signal use (although you do have almost everything for "decorative lighting" usage).

So, can you either ... please ... add these specific signal colors to your mod -OR- make you mod and the above mod..."get along" and not conflict?

Alternatively, put gravel and chainlink fence in their own mod as that's all I use in your mod that I can't seem to find elsewhere.

Regards,
~B

**Comment by jpanther** [comment]
The reason that mod conflicts with Dectorio is that it is written in such a way that overrides the colours after other mods have already processed them. As I mention in the mod description you can add or change any of the signal colours you like, so you can effectively add an unlimited amount by simply placing them in the `config.lua` file. The colours from the more-colours mod you have linked to are as follows, feel free to cut and paste them into the Dectorio config and you can then uninstall more-colours. Or, if you want to avoid the conflict altogether, just disable Dectorio's signals support - it sounds like you're only using the gravel and fences anyway.

```
    {type="virtual", name="signal-hotpink", color={r=1,g=0.41,b=0.7,a=0.5}},
    {type="virtual", name="signal-orange2", color={r=1,g=0.64,b=0,a=0.6}},
    {type="virtual", name="signal-chartreuse", color={r=0,g=1,b=0.5,a=0.5}},
    {type="virtual", name="signal-purple2", color={r=0.5,g=0,b=1,a=0.8}},
    {type="virtual", name="signal-darkpink", color={r=0.5,g=0,b=0.25,a=0.35}},
    {type="virtual", name="signal-darkorange", color={r=0.5,g=0.2,b=0,a=0.45}},
    {type="virtual", name="signal-palegreen", color={r=0,g=0.5,b=0.25,a=0.25}},
    {type="virtual", name="signal-paleblue", color={r=0,g=0.25,b=0.5,a=0.25}},
```

Failing that, you can always use actual items to carry signals. If you need a signal for wood, why not just use the wood item instead of using a brown colour?

**Comment by abordoli** [comment]
Thanks jpanther for the explanation and work-around.

The current issue that I'm running into is being limited to signals themselves. Sure, I can use "Wood" to count all the wood in my "system", but if I want to set a constant for "Maximum Allowed Wood", then I have to think of using some signal (other than the wood item) to represent that for obvious reasons. 

So you get in this quagmire of being limited to 0-9, A-Z, the colors offered and whatever extra signals you can port in from "mods" (like a battery symbol or clock symbol, etc.)

It SEEMS alot at first, but when you pile on complexity ontop of complexity you simply run out or begin using leftovers and then nothing really makes any sense unless you have it all recorded down in a "Legend", etc.

**Comment by jpanther** [comment]
Ah okay, your use case makes sense. There's really an infinite requirement for more signals the larger the factory grows. I may try to add some more colours in a future update. The only reason I haven't so far is to keep it neat and tidy as some of the colours start to look like they are repeating if they are too similar and it gets more confusing for less advanced players. You may have noticed I added some symbol based signals in the last patch too. Do you think more like these would be useful too?

**Comment by abordoli** [comment]
Yes, more symbol based signals would be perfect. I can give you some ideas as to ones that might get a great amount of use....

For example:
Coal-Ore-Max
Stone-Ore-Max
Iron-Ore-Max
Copper-Ore-Max
Iron-Plate-Max
Copper-Plate-Max
Steel-Bar-Max
Stone-Brick-Max

Those 8 would avoid me from having to use 8 of the precious colors. I can give more examples, but I wouldn't want to overwhelm and would be appreciative of just those 8. You can let me know if you want to hear some more.
Thxs!
~B

**Comment by jpanther** [comment]
Let me know more examples, it's better to know the full picture before trying to find the best solution. :)

**Comment by abordoli** [comment]
Well, it'd be too much (and too long a drop-down list in a tab) to create every possible user-case. The goal here is to simply find more appropriate "signals" that symbolize what the signal is stating/measuring/limiting, etc. rather that 0-9, A-Z and the colors given.

**Comment by abordoli** [comment]
Also, please take a look at: https://mods.factorio.com/mods/folk/mydecals

I have some ideas about this #possiblyabandonedmod that may enhance your mod if you annexed its features and replaced the given "decals" with some actual "decorating type stuff". The mind reels and you can always allow the user to export in their own graphic.

**Comment by jpanther** [comment]
I'm closing this issue as Dectorio 0.9.2 adds additional new colours and circuit network signals and at this time I don't see a need to add more.

![signals](https://user-images.githubusercontent.com/4462786/53676651-750fbe00-3cf9-11e9-803d-2abe46e2f66d.png)
