### ISSUE TITLE
migrate config.lua to startup settings

### ISSUE THREAD

**Issue by Yousei9** [jpanther/Dectorio#29]
It's a bit annoying having to unpack and edit the config after updating your mod to keep vanilla concrete recipe.
The 7 settings still in config.lua could easily be migrated to startup settings.

**Comment by jpanther** [comment]
I have been thinking about moving a couple of them. The intent behind creating some of those settings was purely to address one-off requests and so putting all those items in the settings is not really ideal. The vanilla concrete one is the one that seems to cause the most debate so I can definitely see a case for that being configurable in the UI.

**Comment by Yousei9** [comment]
Vanilla concrete is good approximation of actual concrete. No road or pavement is using reinforced concrete.
It would only increase building and maintenance costs and potentially also cause roads to deteriorate faster should some ground water reach the steel frame.

What your recipe implies is reinforced concrete as it is used for walls, building floors and bridges. The only structure where such concrete in Factorio or Dectorio is used are concrete walls.
Creating reinforced concrete walls from vanilla concrete + iron sticks would be more realistic.

**Comment by jpanther** [comment]
Your logic makes sense. I think I'll look to revert this back to the vanilla recipe and then I can remove the option altogether and not need to migrate the settings at all.
