### ISSUE TITLE
Turn off modification of concrete recipe

### ISSUE THREAD

**Issue by ST-DDT** [jpanther/Dectorio#31]
I know there is the huge discussion whether concrete needs iron ore or iron bars,
but in reality recipe for concrete does really need some metal ore.

> It consists of a mixture of calcium silicates (alite, belite), aluminates and ferrites - compounds which combine calcium, silicon, aluminium and iron in forms which will react with water.
(https://en.wikipedia.org/wiki/Concrete#Cement)

I'm sure there are other (more reliable) sources that also claim variants that don't need iron ore and only use the iron bars for reinforcement purposes.
However since Factorio uses the variant with ore (without reinforcements) I would like to keep it that way so i can enable/disable your mod without rebuilding my concrete factory.

**Comment by jpanther** [comment]
Thanks for the info. I've pretty much already decided to revert the concrete recipe to vanilla as it removes the frustration for people to have to manage this change and also simplifies the mod (see issue #29). Instead, iron sticks will be required for the concrete wall.
