### ISSUE TITLE
Ore stack sizes change with gravel enabled: conflict with PickerExtended

### ISSUE THREAD

**Issue by dgw** [jpanther/Dectorio#44]
Having added Dectorio to my game a few days ago (after seeing it in Xterminator's Train Set video series), I was so busy playing with it and several other mods that I didn't notice for some time that Dectorio actually modifies the stack sizes of ores, in addition to flooring tiles and walls.

I've thought about it for a few days, and if it was only stone or only stone and coal, I could live with it. But because _all_ ore stack sizes are changed from 50 to 100, there's just too much logic that would need reprogramming and I don't want to keep the mod installed if it's going to change stack sizes all over the place.

The options have overrides for flooring item and wall item stack sizes, but not for ores (gravel, I guess). So there's no way to keep the gravel options available but use vanilla stack sizes. And I don't really like stack size changes in general, personally—especially for the smelted ores, because fitting the same number of plates in a train as ore units feels wrong somehow.

If there was a simple toggle in Dectorio that disabled all stack size modifications, I'd be a happy camper. Mostly the toggle is for simplicity, so I'd call it "Don't change item stack sizes" or something.

I'd even be happy to create a pull request with this feature, if the suggestion is accepted. I've been meaning to get a little deeper into Factorio modding. :) For now, I'm going to see how (or if) the stack sizes reverting to defaults break my game now that I've disabled Dectorio… This should be fun!

**Comment by jpanther** [comment]
Thanks for your comments, and I agree that changing all those stack sizes is a considerable change to the game however I don't think it's Dectorio that is doing that? As far as I know it's only changing them for concrete and stone bricks. I had a quick look through the code again now and I can't see where it's changing all the ore stack sizes. I know from my own save game where I'm playing with Dectorio and all options enabled the stack sizes are only 50. Are you sure it's not a different mod?

If you can point me to where you think it's happening, I'm happy to stop it from doing this as it's not my intent for the mod to behave like that!

**Comment by dgw** [comment]
I have the anecdotal evidence of disabling Dectorio yesterday and finding that my ore trains once again topped out at 2k/wagon as expected, but I'll have to do some investigating in the other mod packages when I get back to my computer. Like you, I could not find any code in this mod that should be changing ore stack sizes (searched for "iron", "ore", "stack", and "stack_size", plus skimming most of the item prototype files in this repo).

I suspect that the setting I originally suggested is not necessary if the ore stack sizes aren't supposed to change, since the other values changed by the mod are configurable already. If/when I figure out the cause, I'll update the issue title appropriately, but for now a generic description of the real issue will suffice. I'll be back Soon™…

**Comment by jpanther** [comment]
It may be another mod that is looking for prototypes that have the `place_as_tile` attribute set and then modifying the stack size thinking they are flooring. If you can post a mod list for your save it might have some clues.

**Comment by dgw** [comment]
As you might've guessed from the new (again) issue title, I found the culprit. PickerExtended sets all tiles' stack sizes to 100 by default in a data-final-fixes script. I'll have to poke around Nexela's code and/or the settings GUI to see if I can override that without having to set too many tiles' stack size to 50, but the good news is that you're not crazy, and there isn't any mysterious code in this mod changing stack sizes without your knowledge. I'll close this issue as it's confirmed not a bug.

Your pointer was much appreciated, @jpanther. Once I extracted copies of all the mods and started `grep`ping for `place_as_tile`, it was pretty easy to figure out which mod dunnit. Cheers for the help!

**Comment by jpanther** [comment]
I'll also add a note here to say that I've added a new setting to allow toggling of the placing ores as gravel which will prevent this from happening as it will stop the `place_as_tile` attribute from being set on those ores. It will be in the next release.

Ref: 9678cb0bbb2857994ea85d8fd1956ea51ac8097d and [flooring.lua](https://github.com/jpanther/Dectorio/blob/develop/prototypes/item/flooring.lua#L76)
