### ISSUE TITLE
Color Coding Fire Hazard concrete

### ISSUE THREAD

**Issue by justarandomgeek** [jpanther/Dectorio#48]
I just wanted to give you a heads up, that in the 0.16 release of Color Coding i'm removing my Fire Hazard concrete (it's the only one that isn't script generated - the solid colors are easy!), and will be directing users to Dectorio for striped concrete. You don't seem to have solid colors, or fixed-color lamps, so the two don't really overlap other than that.

You might want to add migrations to convert the item `fire-hazard-concrete` and tiles `concrete-fire-left` and `concrete-fire-right` to your red/white striped concrete, for a more seamless user experience.

**Comment by jpanther** [comment]
Thanks for the heads up, I think it's a good idea to remove the crossover and it's easy for me to migrate them over. That way people can use both mods at the same time without getting duplicate functionality. I'm anticipating 0.16 needing quite a few changes in the various tiles so I can just add this in at the same time.

Not sure if I should gate the migration around a certain technology or something but basically, I'll do this:
```
[item]
fire-hazard-concrete -> dect-paint-emergency

[tile]
concrete-fire-left -> dect-paint-emergency-left
concrete-fire-right -> dect-paint-emergency-right
```

You're right that Dectorio doesn't have any solid colours or fixed-colour lamps. I have tried to avoid having too many items that get added and I knew your mod already had that functionality for those who wanted it. My long-term goals for Dectorio are to introduce a whole "Paint" tech tree that allows more variation on a range of items but it's still in my long-term basket for now as I'm waiting to see what happens with the upcoming UI changes and things to see if there's better ways to do it without needing to create lots of new items for all the various colourways.

**Comment by justarandomgeek** [comment]
Yeah, that migration should handle the existing items/tiles they have properly. If your item's recipe is normally gated behind a tech, then they'll have to research that to make more, but the items/tiles they already have they'll get to keep. If you wanted to i guess you could check if colored concrete was unlocked already and unlock things, but it seems no big loss to have to research it again imho.

**Comment by jpanther** [comment]
Yep, makes sense. I'll just bring them across as it is and will ignore any tech requirements.
