### ISSUE TITLE
dectorio-flooring-stack-size option does not affect vanilla hazard concrete

### ISSUE THREAD

**Issue by ST-DDT** [jpanther/Dectorio#56]
The `dectorio-flooring-stack-size` does not affect the vanilla hazard concrete stack size, only the painted concrete provided by Dectorio uses that option.

Could you please change it to affect the vanilla hazard concrete as well?

````json
    "dectorio-painted-concrete": {
      "value": false
    },
    "dectorio-flooring-stack-size": {
      "value": 500
    },
````

**Comment by jpanther** [comment]
Thanks for the suggestion, do you mean you'd like it to change the stack size of hazard concrete even when painted concrete is turned off?

**Comment by ST-DDT** [comment]
Yes, because otherwise it looks a little bit inconsistent.

**Comment by jpanther** [comment]
Yep, I can see how that would be the case. The intent behind the "enable" options in settings is to prevent changes to vanilla items when they are turned off, but the way the stack size setting reads, it probably should apply to everything. To avoid confusion, I think what I'll do is make the stack size change apply to any floor tiles across the board.
