### ISSUE TITLE
placing Landfill with shift click takes grass 1 instead of landfills

### ISSUE THREAD

**Issue by Yousei9** [jpanther/Dectorio#61]
Landfills are a bit inconsistent.
Filling water with landfills takes landfill, but when filling by bots (shift clicking) they require, the much cheaper, grass 1 to fill water instead of landfill.

It should always use landfill and then either take specific floor type placed like any other floor or even more comfortably automatically convert the resulting grass 1 to match surrounding tile type.

While reworking landfill the recipe could be changed from 1 landfill in 0.5s for 20 stone to 10 landfill in 5s for 200.

**Comment by jpanther** [comment]
Thanks for discovering this one. I've never actually shift-clicked landfill so this one didn't come up in my testing! Will look into why this is happening and try to rectify it. Without digging into the code I have a suspicion the problem is that landfill actually places as grass-1 and therefore the logic is confused because there's now a separate grass-1 item and it gets priority over the landfill one.

I'm a bit reluctant to change the recipe though as I find that modding vanilla items like that often upsets people.

**Comment by jpanther** [comment]
Out of interest, do you have the "Landscaping items are blueprintable" option turned on? I noticed the base game prevents landfill from being placed with robots partly because of this issue where it tries to place it as grass-1.

**Comment by Yousei9** [comment]
Yes, I'm using "Landscaping items are blueprintable", otherwise i probably wouldn't have noticed either.

**Comment by jpanther** [comment]
Basically the way this works in the base game makes it incompatible with how I'm trying to do it in Dectorio. Really Landfill isn't meant to be placed by robots and there are other mods that have well implemented workarounds that provide the functionality. I think the cleanest solution to this is to prevent grass-1 from being able to be placed by robots. But if that is the solution, then I'm not even sure if the Landscaping blueprintable option is worth keeping at all.

**Comment by Yousei9** [comment]
So landfill has grass-1 as result and that confuses bots when blueprinting it?
If that's the problem give landfill its own result (looking like piled dirt?) when landscaping is enabled.
That would look realistic and give additional functionality to decorative landscaping.

**Comment by jpanther** [comment]
That's actually not a bad solution! I'm not sure if you've used Alien Biomes before but that is essentially what it does to Landfill too. It's already been frustrating me from a realism perspective that Landfill places as grass-1 even when your base is in a desert biome so a rocky tile would fit in far more comfortably. I'll have a play with some textures and see what looks good.
