### ISSUE TITLE
Gravel changes?

### ISSUE THREAD

**Issue by abordoli** [jpanther/Dectorio#64]
I noticed that gravel had changed in that you can have four colors from each of the main ores. I also see that the gravels are not as heavy on the terrain. I have also noticed that you can no longer mine the gravel.

Are these your findings, too? If so, do you think there'll be a way to mine them back up?
Regards,
Antony

**Comment by jpanther** [comment]
It is correct that there are four types of gravel and you are able to mine them back up while holding any other flooring in your hands.

**Comment by abordoli** [comment]
I crated a sand tile to test that...No luck.

I'll test with others and report back.

**Comment by abordoli** [comment]
I have a modder that might be interested in some of your talents. Can we set up a 3-way? Discord or IRC is fine...

**Comment by abordoli** [comment]
Just tested with cement tile. The stone gravel is not being removed by either having cement in hnd and right-clicking as well as being placed and removed. It's like the gravel is on a layer below tiles.

No worries...I'll just save before applying gravel in the future. Else we could look for mod conflicts. Your choice.
Regards,
Antony

**Comment by jpanther** [comment]
I'll have a look into this and see if I work out why it's not allowing you to remove it. They are on different layers but it shouldn't prevent them being mined. It could well be a mod conflict... there are a lot of mods out there that just change everything instead of only changing the parts that they mod.

**Comment by jpanther** [comment]
I'm unable to replicate this issue and it hasn't been reported by others, so I am closing this one for now. If you have further comments, please reply and I can look into it.
