### ISSUE TITLE
Painted refined concrete?

### ISSUE THREAD

**Issue by HammerPiano** [jpanther/Dectorio#65]
Hi, in version 0.16.27 (of Factorio) new type of concrete was introduced, refined concrete. Will there be painted refined concrete, just like the regular concrete?

**Comment by jpanther** [comment]
Thanks for the suggestion. This should be easy for me to implement. I'll look at adding it in an upcoming release.

**Comment by ST-DDT** [comment]
Also please adjust the stack size similar to the normal concrete.
