### ISSUE TITLE
Gate needs concrete wall

### ISSUE THREAD

**Issue by StephanSteinert** [jpanther/Dectorio#69]
Hi,

the recipe for the vanilla gate needs concrete walls instead of brick walls.

Is this intended?

Cu, Stephan

**Comment by jpanther** [comment]
Thanks for the question. This is intended behaviour as the vanilla gate health and resistance stats have been modified in Dectorio to make them stronger. The stats they have are in line with the concrete wall stats and so it makes sense that they are made of the same materials.

**Comment by StephanSteinert** [comment]
And how should i build normal gates now until concrete is researched?
Even concrete in Angel's is a hole other league.

I suggest to readd vanilla gates and add concrete gates seperately.

**Comment by sdv3** [comment]
Up. 0.17 is out long ago. We need stone gates.

**Comment by sdv3** [comment]
...or wooden gates...

**Comment by jpanther** [comment]
Thanks for your patience with this request. I can finally confirm that the next release of Dectorio will have new Stone and Concrete gate variants. The Stone gate is a cheaper version of the vanilla Gate that better allows tech progression (it doesn't even require steel) and the concrete gate is locked behind a more advanced technology research that better aligns with the strength of concrete walls.

As an additional note, now that the base game supports proper wall-gate patching, I also plan to introduce a gate for the chain-link fence, although that is still in the to-do pile.
