### ISSUE TITLE
Run between concrete walls

### ISSUE THREAD

**Issue by othocaes** [jpanther/Dectorio#73]
Hey mate,

I can run through concrete walls. Thought maybe the collision size got changed. Cheers.

**Comment by jpanther** [comment]
Thanks, this is obviously unintended! I'll do some testing and work out what is going on.

**Comment by jpanther** [comment]
I've been doing some testing on this and I'm unable to replicate the issue. Are you still having this problem? It may be something that is being introduced by another mod (although I've tested it with _Squeak Through_ and don't have any issues).

**Comment by othocaes** [comment]
Yeah, it happens. I figured out later that it seems to be speed-based,
though. It happens if I have sufficient legs in my armor and am running on
concrete. So it might be a simulation thing.

**Comment by jpanther** [comment]
Hmm that is interesting. Is it only concrete wall that does it or is it any wall? I've just tried this in my test game wearing 8 legs (the max I can fit in the base Power Armor MK2) and running on concrete into the wall and can't seem to run through it. How many legs are you using?! I'm still wondering if maybe it's something that is being introduced by another mod?

**Comment by othocaes** [comment]
only 6 legs but I think we started to notice because we also have some tech
for increasing running speed, so the running is very fast.

**Comment by othocaes** [comment]
No other mods are modifying the wall data. But I reeeally think it's the
mod that makes us run very fast.

**Comment by jpanther** [comment]
Closing as this doesn't appear to be a Dectorio issue.
