### ISSUE TITLE
Add search box to sign icon GUI

### ISSUE THREAD

**Issue by jpanther** [jpanther/Dectorio#75]
It would be helpful if the sign icon GUI could be filtered using text search similar to the crafting screen

_Ref: https://mods.factorio.com/mod/Dectorio/discussion/5b0e84e52204af0009d2aaaf_

**Comment by RapidMinimumBeaver** [comment]
Please yes! With angel/bob or Kras this list gets crazy to try and scroll through and find the one little icon you are looking for! I came to the Git page specifically to request this feature :)
