### ISSUE TITLE
Crashing when trying to load with picker tweaks

### ISSUE THREAD

**Issue by magnus97** [jpanther/Dectorio#80]
This has happened for a while now and is due too picker not having the setting that was mentioned in #49 anymore and i tried removing that incompatibility in the config.lua on my own and dident get any errors while loading any save. This is due to it now being its own mod witch is called PickerSignals (as of this issue isent updated to 0.17)

**Comment by jpanther** [comment]
Thanks for the note and PR. This is already fixed in a1039e8684efea3c9ce60d838ba7f724102d8bba and will be in the next Dectorio release.
