### ISSUE TITLE
MP error: "Cannot join. The following command handlers are not identical..."

### ISSUE THREAD

**Issue by marat569** [jpanther/Dectorio#83]
So I'm on 0.6.51, added the mod (Dectorio_0.8.10) to my dedicated server's mod folder and mine, fired up the server, connect to server, and I get an error along the lines of "Dectorio is not a multiplayer supported mod" (Forgot the exact message since this was hours ago)

I see other people making issues about other multiplayer related issues, meaning they are able to at least get into the game with said Dectorio, but I just get a box saying the mod is not made for MP, and can't connect.

So what's up? Would love to have this mod on my server, thanks!

Edit: Here is the error: https://i.imgur.com/DaJg9xJ.png

**Comment by jpanther** [comment]
Thanks for the report. This issue has come up with some people in the past and the workaround is to save the game with the mod installed and then re-host the game from that save. For some reason sometimes when you launch a multiplayer session for the first time with the mod freshly installed (and the map hasn't been saved), it gives this error.

I'm still looking into a more permanent solution.

**Comment by marat569** [comment]
Thank you so much! 

Following your instructions I was able to get Dectorio 0.8.10 on my 0.6.51 server! I can now make my base pretty!

If you do happen to make a permanent solution, update the 0.6.51 version as well (if it's not too much work) -- as some people (me) are not updating to 0.7 for some time c:

**Comment by jpanther** [comment]
Glad it worked. I've been testing a few solutions to this and I think I might have a possible one - at least it's working on my local 0.17 test multiplayer game. I don't usually release updates to prior major builds of Factorio but you probably won't have any issues now you've saved your game and got it working.

**Comment by jpanther** [comment]
@marat569 I noticed you were streaming with Dectorio (thanks!) so I've decided to back port a lot of the fixes from the 0.17 version of Dectorio into a new 0.16 release. You can download v0.8.11 from the Mod Portal and give it a try. If you have any problems, feel free to open a new issue on here.

**Comment by marat569** [comment]
Thank you! I'm curious, is there a reason the newer version is 30mb vs 90mb?

**Comment by jpanther** [comment]
There's better image compression of the graphics assets (Ref: e5e58fe254b885114030e54a42c801807cefe120). It's all still the same features, but it takes up less space. It's another one of the things I added after 0.17 was released.
