### ISSUE TITLE
Error while applying migration:Dectorio : 0.8.9.lua

### ISSUE THREAD

**Issue by Gregerytodd** [jpanther/Dectorio#84]
Got this message when loading saved game,

--Dectorio__/migrations/0.8.9.lau:2: bad
argument #-1 to 'find-entities-filtered' (string
expected, gottable)

Not sure what to do    Thank you

**Comment by jpanther** [comment]
Thanks for the report. Is this on a very old save? Did you have Dectorio installed on that save or have you recently added it?

**Comment by jpanther** [comment]
This should be fixed in v0.9.3. Please try the updated version and let me know if you have any issues.
