### ISSUE TITLE
Crash against Alien Biomes 0.4.1

### ISSUE THREAD

**Issue by SalmonSays** [jpanther/Dectorio#85]
The beta release of Alien Biomes 0.4.1 causes a hard crash right out of the gate alongside Dectorio as a side effect of the optional dependency.

![xYe5Gel](https://user-images.githubusercontent.com/11697389/54076995-017d2c00-4278-11e9-8dce-8d00a371e44c.png)

I imagine deleting 'data-updates.lua' from the main directory is a super temporary workaround for this, but Earendel suggested I post a bug report here as a flag needs to be removed from the item

"the quickbar change means that 2 of the flag settings on items are no longer valid and have to be removed from all items"

**Comment by jpanther** [comment]
Thanks. I’ve been waiting for it to be updated before seeing if it will still be compatible with Dectorio. I just checked the mod portal and don’t see any updated releases? Where is the beta?

**Comment by SalmonSays** [comment]
It's a test version available through Earendel's discord, hopefully he doesn't mind me briefly rehosting it if you just wanna grab it/test for compat yourself-

https://www.dropbox.com/s/exh03b3nbd3hst5/alien-biomes_0.4.1.zip?dl=0

When I asked what's still on the to-do roster before it's no longer a testing version, he said:

"It would probably be ready now, but it's best to avoid making changes to anything that affects terrain generation. I want to get feedback from a few more testers before I put it on the mod portal just in case there are problems I have not found. The main thing on the todo list is improve the transition from snow to not-snow but that can be done later without breaking things so I will update my other mods before that."

**Comment by SalmonSays** [comment]
Update- Alien Biomes 4.1 is now released on the mod portal

https://github.com/jpanther/Dectorio/blob/f23143f5214d4627e73b966799ce7f83b592dba7/prototypes/third-party/alien-biomes.lua#L24

deleting this line seems to resolve the issue properly.

**Comment by jpanther** [comment]
Thanks, looking at this now. It was a long weekend here in Australia so didn't have a chance to get to it sooner.
