### ISSUE TITLE
Error loading item prototypes when also loaded with Alien Biomes in 0.17

### ISSUE THREAD

**Issue by Qwertronix** [jpanther/Dectorio#86]
![image](https://user-images.githubusercontent.com/360217/54167929-a186b100-4442-11e9-8675-7a680cca7ccd.png)

Screencap of the issue. 

`\prototypes\third-party\alien-biomes.lua:24` 

The code for generating alien biomes landscaping tiles is adding the deprecated `goes-to-main-inventory` flag to the item prototypes. 

Removed the flag in a local copy and everything seems to work fine now.

**Comment by jpanther** [comment]
Thanks for the report, this has already been fixed in Dectorio 0.9.6. Update is due out shortly. See Issue #85 for details.
