### ISSUE TITLE
[0.9.6] Error applying migration script 0.8.6.lua

### ISSUE THREAD

**Issue by Yousei9** [jpanther/Dectorio#88]
Installing Dectorio together with alien Biomes on an existing map produces this error:
```
Error while applying migration: Dectorio: 0.8.6.lua
__Dectorio__/migrations/0.8.6.lua:17: attempt to index field 'dect-base-water-green' (a nil value)
```

**Comment by jpanther** [comment]
Thanks for the report. I had a quick glance at this and I suspect it's due to something that's changed in _Alien Biomes 0.4.1_ that I missed when updating the rest of the mod. I'll get this patched and release an update later today.
