### ISSUE TITLE
Add the cracked concrete from .15?

### ISSUE THREAD

**Issue by omarflyjoemacky** [jpanther/Dectorio#89]
Hi There

Love your Dectorio mod! Any chance on adding one more type of concrete, the super old style from .15 (the square concrete you have now is very close, but needs some cracks and a bit darker - like the original Factorio concrete!).

![kWWGVr5](https://user-images.githubusercontent.com/48543237/54332972-be0b2080-45dd-11e9-9d0a-352c8d3b44cd.png)

**Comment by jpanther** [comment]
Hey, thanks for the suggestion. The grid concrete in Dectorio is meant to replicate the look and feel of the old 0.15 concrete. The problem with just bringing the exact 0.15 concrete back is that it was never produced in high resolution so there's no assets that exist that will reproduce the same effect and the way concrete works in the game was changed considerably in 0.16.

There is however another mod that attempts to port the old 0.15 style in the 0.16 way - see [kumpuu/factorio-NewOldConcrete](https://github.com/kumpuu/factorio-NewOldConcrete).

**Comment by omarflyjoemacky** [comment]
Let me just say... thank you. Thank you for your wonderful mod and very thank you for your detailed reply. Will check out NewOldConcrete for sure. Keep up the great work. =)

**Comment by jpanther** [comment]
No problem, if you have any other suggestions, feel free to let me know.
