### ISSUE TITLE
Option to cause Hazard concrete to slow instead of speed up?

### ISSUE THREAD

**Issue by Darkehart** [jpanther/Dectorio#91]
Pretty much what the title says: I would greatly appreciate an option to cause the various warning concrete styles to slow you down instead of granting you the same speed bonus as the unpainted concrete. There was an old mod that did this that still works if you manually update the version number, but it doesn't support refined concrete, much less modded concretes.

https://mods.factorio.com/mod/SafetyFirst

**Comment by jpanther** [comment]
Thanks for the suggestion. I like this idea. Do you have any thoughts on what the speed reduction should be? I see that old mod you referenced drops it to 60%, do you find that is a good amount?

Would it be better if this was configurable or maybe different speeds for different colours of concrete?
