### ISSUE TITLE
Property ageing will be deprecated soon 

### ISSUE THREAD

**Issue by Yousei9** [jpanther/Dectorio#93]
This warning shows in the log for every tile Dectorio adds:

> TilePrototype.cpp:157: ageing in prototype definition, use pollution_absorption_per_second (proposed value is the same) as ageing will be not used soon: ROOT.tile.dect-paint-safety-left

Perhaps it would be a good idea to migrate the property before it is removed and Dectorio causes a nil error on load.

**Comment by jpanther** [comment]
Thanks for noticing this. I read about this change in the recent pollution update but didn't act on it. I'll fix it up in the next release.
